### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by an15m** [p4lang/PI#162]
after runing ` ./configure --with-bmv2 && make` , 
![default](https://user-images.githubusercontent.com/8855703/27363362-9c71a2fe-5666-11e7-99e8-a4df2a21bd47.png)

**Comment by antoninbas** [comment]
Please make sure your version of bmv2 is recent enough

**Comment by an15m** [comment]
@antoninbas should I run `./configure --with-pi` while build bmv2?

**Comment by antoninbas** [comment]
At the moment there are 2 implementations of the PI with bmv2. One lives in the bmv2 repo and is enabled by running configure with `--with-pi`. The other lives in the PI repo and is enabled by running configure with `--with-bmv2`. You don't want to be using both. At the moment I would recommend using the one in the PI repo, which is more complete and better tested. In particular the demo included in this repo (https://github.com/p4lang/PI/tree/master/proto/demo_grpc) uses this one. So no, you should not run configure with `--with-pi` while building bmv2.
