### ISSUE TITLE
Question: Error status for attempted update operations that fail?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#178]
Reference to the code: https://github.com/p4lang/PI/blob/master/proto/p4/p4runtime.proto#L59-L66

Copied here for easy reading:
```
message WriteRequest {
  uint64 device_id = 1;
  Uint128 election_id = 2;
  repeated Update updates = 3;
}

message WriteResponse {
}
```

This question may be due to simple ignorance of Google protobufs on my part, and if so I would appreciate a bit of education.

From the code excerpt above, it appears that a WriteResponse is empty of content, other than perhaps that there is some kind of 'acknowledgement' message that a P4 device received a WriteRequest message.  Is that true, or is there more in the WriteResponse that isn't apparent from the excerpt above?

A WriteRequest can contain many Update objects, e.g. one WriteRequest could attempt to add 100 entries to various tables.

While the expected common case would be that all of those operations succeed, an arbitrary subset of those attempted operations could fail for various reasons (e.g. table full, which for things like hash tables isn't always easily predictable by the controller when it sends the add operations which will fail and which will succeed, as it may not simply be 'current # of entries is > size', but dependent on the exact contents of the search keys).

Do you have any plans for a WriteResponse to include some kind of status indicating which Update operations succeeded, and which failed?  Or is there planned to be some other way for a controller to learn this?

**Comment by antoninbas** [comment]
The `WriteResponse` message used to include a list of status codes. After talking to some gRPC developers, it appears that the best practice is to use the `Status` returned by each RPC call (https://github.com/grpc/grpc/blob/master/include/grpc%2B%2B/impl/codegen/status.h#L30) to notify the client of potential errors. This class includes 1) a global status code, 2) an optional error message and 3) an optional binary string with error details.
I won't get into too many details but 1) will be set to `OK` if and only if all operations in a batch succeeded. For 3) we will use a serialized protobuf message that will provide information about exactly which operation(s) in the batch failed and why (e.g. table was full).
The exact syntax of 3) has yet to be defined, as well as the exact semantics. For example, if an operation in a batch fails, should we give up on all subsequent operations, even if they are to be performed on separate resources (e.g. a different table)?

**Comment by jafingerhut** [comment]
If gRPC requests preserve 'message boundaries', i.e. there is nothing in the path between controller and P4 device that 'fragments' large messages into smaller ones in a way that the P4 device cannot tell that this was done, then it would seem straightforward for such a message to have options for 'continue on failure' or 'stop on first failure'.

I have seen 'continue on failure' used in systems for bulk RIB->FIB updates, where some consistency check background task is responsible for dealing with partial failures.

'stop on first failure' sounds useful for some control plane cases I have seen where you want to implement 'all or none' updates of the data plane.  You could implement 'all or none' using 'stop on first failure', then check for error status, and if anything went wrong, undo the parts that were done.  Just brainstorming here -- not sure how complex you want to get in P4Runtime API definition.

**Comment by antoninbas** [comment]
we are going with "continue on failure" for now (see https://github.com/p4lang/PI/blob/master/proto/docs/p4runtime.md#error-reporting)
I'm personally in favor of having an "all of none" mode for the batches. I'm opening a separate issue #290 to track this.
