### ISSUE TITLE
Devices discovery problem.

### ISSUE THREAD

**Issue by dingrui37** [p4lang/PI#185]
When connecting to a P4 target,  how can I get the status of the target (online or offline) ? RPC is successed?  Or sending message in stream channel is successed?  I think there should be a HELLO-like message in P4Runtime API defination.  At the beginning, sending a hello mesage by write RPC, then the gRPC server will response a message with success or failure. I also want to ask how can I query the status of a specific port? 

![default](https://user-images.githubusercontent.com/22718365/29121674-177b7b4e-7d42-11e7-99fc-fcc38a07d8ae.png)

**Comment by yyetim** [comment]
Master arbitration that's part of the stream is essentially the HELLO handshake, for the trivial case of having no controller slaves.
