### ISSUE TITLE
Question: Is there any Message MasterArbitrationUpdate use case?

### ISSUE THREAD

**Issue by wsx25289** [p4lang/PI#187]
I am studying on RPC StreamChannel which in the file p4runtime.proto, and I would like to know if there is any use case about this RPC, especially examples about how to use Message MasterArbitrationUpdate，thanks.

**Comment by antoninbas** [comment]
Master arbitration support has not been documented yet, nor has it been implemented as part of the open-source gRPC server included in this repository. As a result there are no available examples.

**Comment by wsx25289** [comment]
OK, thanks for your answer
