### ISSUE TITLE
Question:How can I get the device-id from packet-in?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/PI#207]
Hi, @antoninbas I have a question about packet-in. When the controller received the packet-in, it only knows which channel the packet come from, but doesn't know which device. How can I get the device id from packet-in in the controller? In my opinion, many devies can share the same grpc channel, like below.
![default](https://user-images.githubusercontent.com/22718365/30839045-d7beabc2-a2a1-11e7-9164-c0eca722ae3b.png)
There is a similar quesion to packet-out, when the controller want to send a packet to the a specific device, 
how to do this? I think if the controller want to know the device id from packet-in, the best way is to use the `PacketMetadata` , how to write the P4 programe? Is there a field list that the `PacketMetadata ` supported? As for packet-out, when the controller want to send a packet to the a specific device, it should encapsulate the device id in the  `PacketMetadata `, if didn't  encapsulate the device id field,  the packet will send to all devices in this channel. Have I understood correctly? Please correct me.

```
// Packet sent from the controller to the switch.
message PacketOut {
  bytes payload = 1;
  // This will be based on P4 header annotated as
  // @controller_header("packet_out").
  // At most one P4 header can have this annotation.
  repeated PacketMetadata metadata = 2;
}

message StreamMessageResponse {
  oneof update {
    MasterArbitrationUpdate arbitration = 1;
    PacketIn packet = 2;
  }
}

// Packet sent from the switch to the controller.
message PacketIn {
  bytes payload = 1;
  // This will be based on P4 header annotated as
  // @controller_header("packet_in").
  // At most one P4 header can have this annotation.
  repeated PacketMetadata metadata = 2;
}

// Any metadata associated with Packet-IO (controller Packet-In or Packet-Out)
// needs to be modeled as P4 headers carrying special annotations
// @controller_metadata("packet_out") and @controller_metadata("packet_in")
// respectively. There can be at most one header each with these annotations.
// These special headers are captured in P4Info ControllerPacketMetadata.
message PacketMetadata {
  // This refers to Metadata.id coming from P4Info ControllerPacketMetadata.
  uint32 metadata_id = 1;
  bytes value = 2;
}
```

**Comment by antoninbas** [comment]
There is a single `StreamChannel` bi-directional stream per (connector, device) pair. Do not confuse with a gRPC channel, which is more like a transport and a totally different thing. A connector can open a single gRPC channel to a multi-device chassis, but will multiplex multiple `StreamChannel` streams -one per device- over that channel.
The first thing a controller needs to do when it opens the stream is send a `MasterArbitrationUpdate` message (https://github.com/p4lang/PI/blob/master/proto/p4/p4runtime.proto#L363), advertising its election id. This message includes a device id. All subsequent arbitration & packet IO messages on that stream will be for that device. So no, you do not need metadata for this, you just need to be able to map the stream to the device id.
The simple_switch_grpc unit tests have been updated to include that `MasterArbitrationUpdate` message. See https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/tests/base_test.cpp#L49

**Comment by antoninbas** [comment]
By the way, if you have additional question on arbitration, please make sure you read this document first: https://github.com/p4lang/PI/blob/master/proto/README.md

**Comment by dingrui37** [comment]
Thanks @antoninbas , I think I was confused by the grpc channel and stream channel. Stream channel is over the same grpc channel, grpc channel is over the tcp layer. My understanding is shown below，is it right?

![2017-09-26_152152](https://user-images.githubusercontent.com/22718365/30847554-8387e08c-a2ce-11e7-9f6a-60f3e7398a42.png)

**Comment by antoninbas** [comment]
That looks correct.
