### ISSUE TITLE
Question: some questions about extern entry and action profile.

### ISSUE THREAD

**Issue by dingrui37** [p4lang/PI#220]
1) What is the meaning of `ExternEntry`? Is there a relationship with the `extern `keyword in the P4_16 version? Can you give me an example? 
2) I didn't see the `action_profile` keyword in the P4_16 version，perhaps with `extern ` instead, so are messages `ActionProfileMember ` and `ActionProfileGroup` only support for the P4_14 version?
3) Some action profiles use `dynamic_action_selection`  to choose a particular entry within a group, but
the group itself has a choice mechanism，such as `SELECT`, `FAST_FAILOVER`, `weight` and `watch `. What is the relationship between the attributes of the group itself and the dynamic selector?

**Comment by antoninbas** [comment]
I suggest you read the Portable Switch Architecture (PSA) specification: https://p4lang.github.io/p4-spec/docs/PSA.html
If you read the P4 API Working Group charter (http://p4lang.github.io/p4-spec/docs/P4_API_WG_charter.html), you will see that PSA externs have been given a special status and are part of the base P4 Runtime interface definition. These extern includes action profiles, counters, meters, ...
If you are interested in keeping up with the work of the P4 API Working Group, I suggest that you subscribe to our mailing list: http://lists.p4.org/mailman/listinfo/p4-api_lists.p4.org. The list is reserved to p4.org members, but if I remember correctly you work for ZTE, which is a member organization. After joining the mailing list, you can also choose to attend the biweekly WG meetings.

**Comment by dingrui37** [comment]
I did work in ZTE， I will adopt your suggestion. Thanks.
