### ISSUE TITLE
Add --json <file> to 1sw_demo.py launch instructions

### ISSUE THREAD

**Issue by technobilly** [p4lang/PI#227]
PI/demo$ sudo python 1sw_demo.py --cpu-port veth250
usage: 1sw_demo.py [-h] [--thrift-port THRIFT_PORT] [--dev-id DEV_ID]
                   [--num-hosts NUM_HOSTS] --json JSON [--pcap-dump PCAP_DUMP]
                   [--cpu-port CPU_PORT]
****1sw_demo.py: error: argument --json is required****

Works:
$ sudo python 1sw_demo.py --cpu-port veth250 --json simple_router.json 
*** Creating network
...

**Comment by antoninbas** [comment]
I'm not sure I understand this issue.
- if you are talking about PI/demo, then I do not see a README file, so which instructions are you referring to? By the way, this demo is out-of-date and may be removed soon.
- if you are talking about PI/proto/demo_grpc, then the instructions are correct: the switch should be started without a JSON file, the file is pushed later through P4 Runtime.

**Comment by chrispsommers** [comment]
Antonin, I can't reproduce my problem, I must have had some path confusion. I was talking about PI/proto/demo_grpc. I guess this can be closed. Thanks.

**Comment by antoninbas** [comment]
I think you may have tried to use the PI/demo/1sw_demo.py script to run the PI/proto/demo_grpc demo.
