### ISSUE TITLE
Core dumped when running the examples

### ISSUE THREAD

**Issue by Yukinarii** [p4lang/PI#230]
Hello,I just tried to run the examples/example_1 & example_2,and got a core dumped message in both cases as follow:
Assertion '!add_route(ipv4_dstAddr, 8 , ipv4_dstAddr, port, &handle)' failed, file 'example_1.c' line 103 has terminated (core dumped)

steps:
simple_switch examples/testdata/simple_router.json  // to start the switch
./example_1

**Comment by antoninbas** [comment]
Fixed with https://github.com/p4lang/PI/pull/235
Note that these examples don't work with bmv2. They use the "dummy" PI implementation, for which every table operation is a no-op.
