### ISSUE TITLE
seg fault in demo_grpc controller

### ISSUE THREAD

**Issue by technobilly** [p4lang/PI#231]
In three separate terminals, per demo_grpc/README.md

PI/proto/demo_grpc$ sudo python 1sw_demo.py --cpu-port veth250
PI/proto/demo_grpc$ ssudo ./pi_grpc_server
PI/proto/demo_grpc$ s`sudo ./controller -c simple_router.json -p simple_router.p4info.txt
Segmentation fault (core dumped)

Use GDB to trace:

PI/proto/demo_grpc$ gdb ./.libs/lt-controller 
...
(gdb) r -c simple_router.json -p simple_router.p4info.txt
Starting program: /home/chris/p4/PI/proto/demo_grpc/.libs/lt-controller -c simple_router.json -p simple_router.p4info.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3366700 (LWP 29052)]
[New Thread 0x7ffff2b65700 (LWP 29053)]

Thread 1 "lt-controller" received signal SIGSEGV, Segmentation fault.
0x00007ffff5644650 in grpc_completion_queue_factory_lookup () from /usr/local/lib/libgrpc.so.5
(gdb) bt
#0  0x00007ffff5644650 in grpc_completion_queue_factory_lookup () from /usr/local/lib/libgrpc.so.5
#1  0x00007ffff799eee1 in grpc::CompletionQueue::CompletionQueue (this=0x669120) at /usr/local/include/grpc++/impl/codegen/completion_queue.h:106
#2  grpc::ClientReaderWriter<p4::StreamMessageRequest, p4::StreamMessageResponse>::ClientReaderWriter (context=0x668ec8, method=..., channel=0x6682a0, 
    this=0x669100) at /usr/local/include/grpc++/impl/codegen/sync_stream.h:328
#3  p4::P4Runtime::Stub::StreamChannelRaw (this=0x669060, context=context@entry=0x668ec8) at grpc_out/p4/p4runtime.grpc.pb.cc:72
#4  0x000000000040ffad in p4::P4Runtime::Stub::StreamChannel (context=0x668ec8, this=<optimized out>) at ../grpc_out/p4/p4runtime.grpc.pb.h:117
#5  StreamChannelSyncClient::StreamChannelSyncClient (channel=..., simple_router_mgr=0x7fffffffd650, this=0x668eb0) at simple_router_mgr.cpp:186
#6  SimpleRouterMgr::SimpleRouterMgr (this=0x7fffffffd650, dev_id=<optimized out>, io_service=..., channel=...) at simple_router_mgr.cpp:231
#7  0x000000000040f0a0 in main (argc=<optimized out>, argv=<optimized out>) at app.cpp:117

I rebuilt protobufs and grpc from source. Here is version:

PI/proto/demo_grpc$ protoc --version
libprotoc 3.0.0

Somehow I think this is a lib mismatch or something. Thanks.

**Comment by chrispsommers** [comment]
After syncing and rebuilding from latest repo the problem disappears. It must have been a local env issue. This can be closed, thanks.
