### ISSUE TITLE
Document P4Info

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#234]
Documenting P4Info is just as important as documenting the P4Runtime service, as the 2 go hand-in-hand.
Documentation should include information on how to extend P4Info for target-specific extern entities.

**Comment by aghaffarkhah** [comment]
Need to ask for Tom's help.

**Comment by antoninbas** [comment]
Maybe some details are still missing, but we do have sections for all P4Info entities in the spec thanks to Carmelo.
