### ISSUE TITLE
Are control plane writes to register entries supposed to be atomic relative to data plane accesses?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#236]
If this is already addressed in the P4 Runtime API docs anywhere, a pointer would be appreciated.

For P4 tables, only the control plane adds, deletes, or updates entries, so it is straightforward (or at least maybe easier) to make such updates atomic relative to packet forwarding (meaning, every control plane update is implemented such that it effectively occurs 'between' two packets accessing the table being updated).

For P4 registers, the common mechanism for P4 programs to access them is to read an entry from an index, do some calculations, then write back a possibly modified value to the same index.  More general patterns of access on a single register instance, or across multiple register instances, are certainly possible to write P4_16 code for, although which of those a target supports is target-dependent.

Even for the simplest case, if the control plane wrote an entry of a register, and it physically happened between the time that the data plane read an entry, and wrote it back, the effect of the control plane write could be lost.  That may be acceptable for some use of registers, but if you have a use case for a register where that isn't correct behavior, is there anything in P4 Runtime API that is intended to guarantee that behavior?

**Comment by antoninbas** [comment]
I don't believe this is a P4 Runtime issue.
The P4_16 spec describes the concurrency model for P4 programs (https://p4lang.github.io/p4-spec/docs/P4-16-v1.0.0-spec.html#sec-concurrency). In particular it states that execution of an action is atomic, which would mean that as long as you read / modify / write the register within the same action, the read and the write would happen atomically with respect to the control-plane operations. The spec also introduces an `@atomic` annotation to let the compiler know that larger blocks of code need to be executed atomically.

I don't know where the guarantee of atomic execution of actions comes from. I know that this has been enforced in bmv2 for a while, even dating back to P4_14 (exactly to support the use case you described). I expect that some targets will not be able to enforce this for more complex actions.

Anyway, from a P4 Runtime perspective, I think the only guarantee should be that **P4 Runtime control-plane operations are themselves atomic**, e.g. you cannot have one half-modified register cell or one half-modified action data list (for a table entry modify operation), and that **they respect the P4_16 concurrency model**, e.g. a control-plane register write cannot "physically" happen in the middle of a data-plane action execution.

**Comment by jafingerhut** [comment]
Thanks.  Maybe I can try with the P4_16 language work group to see if it is worthy of a mention there somewhere.

**Comment by jafingerhut** [comment]
OK, forgot I had already tried this there, and at least some people believe it does belong in the API spec: https://github.com/p4lang/p4-spec/issues/377

@mbudiu-vmw @vgurevich @antoninbas Maybe you guys could pick a spec and we can add a few sentences to it somewhere?  We can always leave these things unsaid, of course, but someone making control plane updates is going to want to know the answers to such questions.

**Comment by mbudiu-vmw** [comment]
I really believe that this is an architecture-specific topic. I really don't know enough about the various possible switch implementations to promise that all of them will have atomic control-plane updates.
First, we don't know what the set of control-plane updates is; some targets may expose different control-plane APIs, e.g., remove all actions in a table. Second, some targets may be perfectly happy with a best-effort API, where transiently packets could see inconsistent control-plane-mediated state.

So I think that each architecture specification should indicate for each control-plane operation whether it is supposed to be atomic. We cannot make a blanket statement in the P4-16 spec about this.

**Comment by jafingerhut** [comment]
I have finally opened my eyes and read the section that Antonin referenced in his comment above in the P4_16 v1.0.0 language spec, and it say right there in Section 16.4.1 "Concurrency model": "Architecture specifications should describe in detail the interactions between the control-plane and the data-plane."

So this issue should be addressed in the PSA, and I will raise it there.

**Comment by jafingerhut** [comment]
Closing this issue in favor of addressing the questions in the PSA spec.

Reference to issue for PSA spec: https://github.com/p4lang/p4-spec/issues/525
