### ISSUE TITLE
digest support in P4 Runtime

### ISSUE THREAD

**Issue by mariobaldi** [p4lang/PI#239]
Add support for digest from data plane in P4 runtime.

**Comment by antoninbas** [comment]
Some more context:
digest is an extern in PSA that enables efficient streaming of data from the data-plane to the control-plane (without having to send the whole packet)
PSA implementations are required to support a digest mechanism
The expectation is that P4 Runtime would support opening a stream to the device to retrieve these digests. It seems that this can easily be done using the `Read` RPC, so nothing would need to change except for the definition of a `Digest` entity protobuf message.
See the PSA spec for more information on digest: https://p4lang.github.io/p4-spec/docs/PSA.html#sec-packet-digest

**Comment by antoninbas** [comment]
Initial proposal for digest support: https://github.com/p4lang/PI/pull/242

**Comment by antoninbas** [comment]
Support has been added to p4info.proto and p4runtime.proto; I'm closing this issue in favor of #345 (implementation request).
