### ISSUE TITLE
support missing PSA externs / features in P4 Runtime

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#241]
This is a superset of #239 which requests support for the `digest` extern.
The following may require additional support from P4 Runtime:
- QoS: it is unclear whether this belongs in the P4Runtime service or is considered a configuration entity
- Packet Replication Engine (PRE): P4Runtime service or configuration entity?
- Buffering Queueing Engine (BQE): P4Runtime service or configuration entity? which control-plane operations are needed for the BQE?
- `Register<T,S>`: need P4Runtime entity
- `Random<T>`: need P4Runtime entity
- `ValueSet<T>`: need P4Runtime entity
- Timestamps: P4Runtime service or configuration entity?
- `Digest<T>`: need P4Runtime entity

Some of these may not be supported directly in the P4Runtime service (p4runtime.proto), but may be punted to an external configuration channel.

Some potential challenges:
- For extern using generics / type-variables (e.g. `Register<T,S>`), we need a way to expose the types in P4Runtime. `T` could be a header type, a struct, a tuple, a header stack, a header union,... A serialized field of bytes doesn't even work if we want to support unions.
- For `Digest<T>`, we need to establish a bi-directional stream between the client and the server. Server sends data to the client, which needs to "acknowledge" them after processing them.

**Comment by antoninbas** [comment]
We may need to create new issues for each extern that needs to be supported, as we start discussing each one.

**Comment by jafingerhut** [comment]
This might be under your category of QoS, but PSA defines that an implementation may have multiple class_of_service values (or just one, class 0).  At a minimum, seems that the control plane might want to get how many classes of service the device supports, and what their identifying numbers are.  0 should always be in the supported set.

**Comment by jtardo** [comment]
This also applies to match kind but in a more complicated way. PSA adds Selector and Range match types. But match kinds are hard-wired in P4Runtime, including Range. Points out the need for a way to make FieldMatch extensible.

**Comment by antoninbas** [comment]
I'm going to go ahead and close this. If something is required and missing from the current spec (https://github.com/p4lang/p4runtime) we can open a more targeted issue.
