### ISSUE TITLE
Question: Document that describes how P4_16 program object names become control plane names?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#243]
[p4c-issue486.zip](https://github.com/p4lang/PI/files/1512291/p4c-issue486.zip)
One of the big changes from P4_14 to P4_16 is that every control in P4_16 is effectively its own "namespace", by which I mean that table names like "t1", action names like "a1", extern instance names for controls, meters, registers, action profiles, action selectors, digests, etc., can all be used an arbitrary number of times in different controls, and for externs, also in parsers.

I intentionally put "namespace" in quotes since it isn't a namespace like in C++ and some other languages.

Another significant change is that controls can have run-time parameters, and thus the local name in a control C1 for a big struct of headers might be "my_headers", whereas in the "ingress" and "egress" control blocks it might be called "hdr".  In table definitions, the same header field could look like "hdr.ipv4.ttl" in the ingress control block, but "my_headers.ipv4.ttl" in control C1.  This currently is visible in the p4runtime files generated by the open source compiler p4c.  Maybe that is the best one can hope for, and if you want to avoid it, you should choose consistent names for control parameters throughout your program, and/or use P4_16 annotations to modify the control plane names.

For an example, see the P4_16 program name-collision-table.p4 in the attached ZIP file (this is a duplicate of a ZIP file attached to p4c issue #486, hence the name).  The table named "guh" comes through in the p4runtime file named exactly the same way twice, even though one is in the ingress control block, the other in egress.

Some questions:

+ Is it intended that all P4_16 programs with legal names (according to P4_16's naming rules, which I'm not sure are explicit yet in all cases) should generate p4runtime files with non-conflicting names, without requiring the use of P4_16 annotations that modify the control plane names?

+ Is it intended that P4_14 programs be auto-translatable to P4_16 programs that generate the same p4runtime info?

It seems that having some explicit documentation explaining how p4runtime names are constructed for P4_14 and P4_16 programs, in the absence of annotations that modify them, would be useful, as well as P4_16 test programs that try to conflict on as many names as possible, to look for mistakes in that documentation.

**Comment by DGeorgeNetro** [comment]
I would like to see duplicate "@name" annotations being illegal. An "@name" should absolutely, 100%, be the name for the entity reported to the control plane without any ambiguity or namespace mangling.

For P4-16 and without "@name" I think the full hierarchical context mixed along with the entity makes sense, ie "ingress_flow.sub_control_flow.my_table" or "hdr.ip_union.ipv4". I think it is sensible for there to be no conflicts without the annotations in place, the annotation should be optional. No one will say they make the code prettier.

For P4-14 I would expect the name to match the entity in the source.

I also think it is time to make duplicate names in P4 programs errors. I know this was done a lot in switch.p4, where a table and an action had the same name, but I think this is a bad idea and complicates the whole name issue.

**Comment by jafingerhut** [comment]
@antoninbas Does this seem worth filing an issue in the p4lang/p4c repository for the code that implements the `--p4runtime-file` option?  If so, I'm happy to do that.

**Comment by jafingerhut** [comment]
Created this issue for p4lang/p4c with a suggested change in its implementation of generating names: https://github.com/p4lang/p4c/issues/1073

**Comment by mbudiu-vmw** [comment]
The P4-16 spec has a section on how names are generated.

**Comment by jafingerhut** [comment]
Understood.  Does it match your understanding that today's --p4runtime-file implementation in p4c-bm2-ss does not match what that section says?

**Comment by mbudiu-vmw** [comment]
Yes, that is correct. Control-plane names have to include the entire hierarchy.

**Comment by jafingerhut** [comment]
Given that p4c issue https://github.com/p4lang/p4c/issues/1106  (and a couple of related ones) have been fixed in p4c and closed, it seems like this one could be closed, too.  Feel free to reopen it if you believe there is something remaining in this issue that has not been addressed.
