### ISSUE TITLE
Should providing a non-zero (i.e. non-default) priority value for a non-ternary match-table be an error?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#253]
The priority field should only be used when the match table includes a ternary / range match.
Should we silently ignore the priority are fail with an INVALID_ARGUMENT error?

**Comment by chrispsommers** [comment]
IMO we should fail in order to alert a programmer that the API is being used incorrectly.  Silent errors tend to accumulate.

**Comment by antoninbas** [comment]
@wmohsin @aghaffarkhah @teverman any thoughts?

**Comment by aghaffarkhah** [comment]
In our stack we are currently failing the call when priority is given in this case.

**Comment by wmohsin** [comment]
+Samar

Capturing the summary from the meeting on this topic:

Externally: The table-entry would be failed with an INVALID_ARGUMENT error

Internally: To help with migration, switch-stack will hold onto priority in
software (and return it in a subsequent Read), but otherwise ignore it.

**Comment by antoninbas** [comment]
The decision is to return an INVALID_ARGUMENT error, there seems to be consensus on this issue.
Will close once the reference implementation and the spec have been updated.
