### ISSUE TITLE
how do we use PI to control simple_switch_grpc?

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/PI#267]
Hi,

In the readme.md, there is an example for simple_switch. Can we use PI to control simple_switch_grpc?

I try this command, but after running, nothing outputs :

![image](https://user-images.githubusercontent.com/12800168/34324312-508cd81a-e8a9-11e7-8d3b-30cc279789bf.png)

Thank you very much, Happy Christmas!

**Comment by antoninbas** [comment]
These tools (the PI CLI and the pi_CLI_rpc binary) predate the P4 Runtime project and should be considered deprecated. They will not work with simple_switch_grpc without some modifications to the build system.

If you want to control simple_switch_grpc, you should use the P4Runtime Protobuf / gRPC interface defined in this file: https://github.com/p4lang/PI/blob/master/proto/p4/p4runtime.proto
If you are not familiar with Protobuf and gRPC, I suggest you read about them first. simple_swith_grpc includes a P4Runtime gRPC server. You can generate P4Runtime library code in the language of your choice using the Protobuf compiler and write your own client code around it. By default this repository will generate, build and install the code for C++ and Python providing the dependencies are met: you need to install Protobuf & gRPC as directed in the README and `configure` the PI repo with `--with-proto`. You are free to run the protobuf compiler yourself to generate bindings in the language of your choice. You can find a toy client application written in C++ (using the P4Runtime C++ code generated by protobuf) here: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch_grpc/tests/example.cpp.
