### ISSUE TITLE
Question of Action Profile Member and Action Profile Group

### ISSUE THREAD

**Issue by tomyhu1995** [p4lang/PI#268]
Hi all, 

I am wonder that the main purpose of Action Profile Member and Action Profile Group. There is no comment in p4runtime.proto.

Hope that someone can help me.

Thanks a lot

**Comment by antoninbas** [comment]
You need to be familiar with both the P4_16 language specification (https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.html) and the PSA architecture specification (https://p4.org/p4-spec/docs/PSA-v0.9.0-draft.html) if you want to fully understand the p4runtime.proto interface definition.

P4Runtime treats PSA extern types as first-class citizens and "action profile" is one such extern. The PSA spec describes the dataplane behavior of the action profile extern, which will help you understand the necessary control-plane operations for it and why p4runtime.proto was written this way.

**Comment by tomyhu1995** [comment]
Hi @antoninbas

Very very very thanks for your reply. Those ideas help me a lot

Thanks again.

Please close this issue
