### ISSUE TITLE
Require that `value == value & mask` for ternary matches.

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#274]
Should we make this a requirement in order to have a canonical representation of ternary matches?
The P4Runtime server would be require to reject the `TableEntry` with an `INVALID_ARGUMENT` error.

**Comment by jafingerhut** [comment]
This seems like a reasonable requirement for the API to me.  If any control plane code generated ternary entries that did not conform to this restriction, it seems like it ought to be easy to detect at the P4 Runtime API interface, and makes it quicker to detect attempts to add duplicate entries.

Control plane code that violated this restriction could do a 'quick fix' of replacing value with 'value & mask' just above calls to the P4Runtime API.  I have worked with buggy control plane code that violated this where 'the right fix' several software layers higher was much more difficult to determine, but I don't off-hand know of any reason why the 'quick fix' would be incorrect in such situations.

**Comment by antoninbas** [comment]
Thanks for your comment @jafingerhut, I have opened PR #279 to address this issue and move forward since no one has objected to this change.
