### ISSUE TITLE
Add brief and detailed description fields for all entities and match fields

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/PI#275]
In theory, P4 Info should provide enough information to write control-plane programs without any access to the P4 source code (if it even exists as such - some implementations might not have actual P4 source to begin with) and without supplemental documentation, which is laborious and tends to lag the code. P4 info (and most P4 source code out there) is lacking in detailed comments describing each entity and match field. We should take lessons from Yang and even SNMP.

The added info would be useful in various ways:

- Users can read p4info text file to understand the meaning and usage of entities and match fields.
- Code-generation or runtime engines could present the info as help for users (e.g. PI CLI or it's successor)
- A potential future IDE (e.g. an Eclipse plugin) could present the help as you develop control-plane code
- Documentation generator similar to Doxygen could construct convenient manuals (we could do same with P4 source itself, but it might not be available).

I therefore propose that P4 info contain a Documentation message which can be added to Preamble and MatchField messages, e.g. :

message Documentation {
  // A brief description of something, e.g. one sentence
  string brief = 1;
  // A more verbose description of something
  string description = 2;
}

message Preamble {
...
  // Documentation of the entity
  Documentation doc = 5;
}

message MatchField {
...
  // Optional per-field documentation
  Documentation doc = 6;
}

Where does this info come from?
The documentation fields could initially be embedded into the P4 source code as annotations and later as first-class language constructs or Doxygen-style comments if we want to evolve the language itself. In the interim,  when such an annotation is recognized, a special compiler mode could emit or copy the info fields from the "annotations" area to the respective Doc area in the resulting P4 info.

Comments anyone? I'm working on some code to try this out.

**Comment by chrispsommers** [comment]
I've got a prototype implementation at https://github.com/chrispsommers/PI/tree/p4info-doc-entities/proto/p4/config with some related samples and utilities at https://github.com/chrispsommers/PI/tree/p4info-doc-entities/proto/p4info/xform

I propose the above-mentioned enhancements to the p4info.proto file and a way to use @annotations() in P4 source code to populate the new fields.

**Comment by antoninbas** [comment]
I added this to the v1.0 milestone as was decided at the 02/07/18 WG meeting.

**Comment by antoninbas** [comment]
Done in #308
