### ISSUE TITLE
Add package-level documentation fields to P4 Info.

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/PI#276]
A controller may wish to manage a library of P4 programs to install on targets. Including more package-level documentation in the P4 info would benefit by allowing a controller/user to browse/introspect the packages. I therefore propose the following:

**1. Create this message same as proposed in #275 (or whatever we settle on):**

message Documentation {
// A brief description of something, e.g. one sentence
string brief = 1;
// A more verbose description of something
string description = 2;
}

**2. Create this new top-level package message. This is just a first idea, I'm open to suggestions.**

message PkgInfo {
	// brief and detailed descriptions
	Documentation doc = 1;
	// a definitive name for this configuration, e.g. switch.p4_v1.0
	string name = 2;
	// configuration version
	string version = 3;
	// date the confiuration was built or compiled
	string build_date = 4;
	// the toolchain used to build it, e.g. "p4c-bm2-ss v 0.0.5"
	string compiler = 5;
	// the target architecture, e.g. "bmv2 simple-switch"
	string target = 6;
	// organization which produced the configuration, e.g. "p4.org"
	string organization = 7;
	// contact info for support,e.g. "tech-support@acme.org"
	string contact = 8;
	// url for more information, e.g. "http://support.p4.org/ref/p4/switch.p4_v1.0"
	string url = 9;
}

**3. Add PkgInfo to P4Info:**

message P4Info {
 ...
  // Top-level package documentation, i.e. for the forwarding pipeline config
  PkgInfo pkg_info = 10; // [chris] This probably should be first element
}

**Where does this info come from?**
The documentation fields could initially be embedded into the P4 source code as annotations and later as first-class language constructs or Doxygen-style comments if we want to evolve the language itself. In the interim, when such an annotation is recognized, a special compiler mode could emit or copy the info fields from the "annotations" area to the respective PkgInfo area in the resulting P4 info.

**Comment by chrispsommers** [comment]
I've got a prototype implementation at https://github.com/chrispsommers/PI/tree/p4info-doc-entities/proto/p4/config with some related samples and utilities at https://github.com/chrispsommers/PI/tree/p4info-doc-entities/proto/p4info/xform.

Propose the above PkgInfo message. Provided a utility to populate an existing P4Info Message with the new Message (from command-line) until a solution is found on how to embed (and extract) it from P4 source code. This could require language changes or simple coding conventions, e.g. Doxygen-style comments which are parsed into P4Info; or specially-designated variables e.g. const struct pkgInfo_t PkgInfo which can be annotated.

**Comment by chrispsommers** [comment]
Updated PkgInfo to include annotations, to allow for extending with arbitrary k-v pairs of metadata:

```
message PkgInfo {
	// a definitive name for this configuration, e.g. switch.p4_v1.0
	string name = 1;
	// configuration version
	string version = 2;
	// brief and detailed descriptions
	Documentation doc = 3;
	// Miscellaneous metadata, free-form; a way to extend PkgInfo
	repeated string annotations = 4;
	// date the configuration was built or compiled
	string build_date = 5;
	// the toolchain used to build it, e.g. "p4c-bm2-ss v 0.0.5"
	string compiler = 6;
	// the target architecture, e.g. "bmv2 simple-switch"
	string target = 7;
	// organization which produced the configuration, e.g. "p4.org"
	string organization = 8;
	// contact info for support,e.g. "tech-support@acme.org"
	string contact = 9;
	// url for more information, e.g. "http://support.p4.org/ref/p4/switch.p4_v1.0"
	string url = 10;
}
```

**Comment by antoninbas** [comment]
I added this to the v1.0 milestone as was decided at the 02/07/18 WG meeting.

**Comment by antoninbas** [comment]
Done in #308
