### ISSUE TITLE
Include application-oriented match-field and action-param type into P4 info

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/PI#277]
Currently p4info and the P4 language are unaware of the "application" semantics of match-fields with commonly used "implied" data types such as dotted-decimal IPv4, colon-separated IPv6, etc. Instead they just know bit fields. It could be handy to include this information so that control-plane code and application code could automatically present appropriate APIs, generate user interfaces and perform verification. Some reference or commercial implementations have helper functions which parse a user-entered string such as "10.11.12.13" and infer the type to be 32-bit, but that is not quite the same as explicit typing. 

Some suggestions for types to declare:

IPv4-addr
IPv6-addr
mac-addr
portnum
vlanID
enum (named values)
int (optional range)
programmer-defined types

The type could be another message field in matchField. I'm thinking that types would be named, and a list of types could be embedded in the P4 info and/or referenced from a known list of TBD standard types which could be imported or similar.

**Where does this info come from?**
The type fields could initially be embedded into the P4 source code as annotations and later as first-class language constructs if we want to evolve the language itself. In the interim, when such an annotation is recognized, a special compiler mode could emit or copy the info fields from the "annotations" area to the respective type area in the resulting P4 info.

yang provides a good example of how to represent types

I'd like to get some feedback before I go further with this.

**Comment by chrispsommers** [comment]
I've got a prototype implementation at https://github.com/chrispsommers/PI/tree/p4info-doc-entities/proto/p4/config with some related samples and utilities at https://github.com/chrispsommers/PI/tree/p4info-doc-entities/proto/p4info/xform

Propose the following:
```
// optional attribute of match fields and action params, can assist the control plane
enum TypeHint {
  NONE = 0;       // no type specified
  OTHER = 1;      // some type not in this list
  MAC_ADDR = 2;   // 48-bit mac address
  IPV4_ADDR = 3;  // 32-bit IPv4 address
  IPV6_ADDR = 4;  // 128-bit IPv6 address
  L4_PORT = 5;    // Layer 4 port 0-65535
  VLAN_ID = 6;    // VLIAN ID 0-4095
  ENUM = 7;       // enumerated type, choose one value only
  BIT_MASK = 8;   // bit mask, one or more bits may be set, bit positions should be declared as an enum type
}

// Optional application-oriented type information for match fields and action params
// Can be used by control plane API and UI generators to provide a more useful
// presentation, e.g. dotted-decimal IPv4 instead of 32 bit string
message TypeInfo {
  // an enumerated specifier of the type
  TypeHint type_hint = 1;
  // possible named type, pending work on serializeed types in P4 LDWG
  string type_name = 2;
}
```

Add the ```TypeInfo``` to ```Table.Matchfield``` and ```Action.Param```. Populate with @annotations() for now, later consider language enhancements.

**Comment by chrispsommers** [comment]
Also  we need a way to include a list of (serializable) datatypes which hopefully can come out of the LDWG:

```
// FUTURE: List of embedded type definitions, pending P4 serialized types in LDWG
// message Types {
//   named type as appears in P4 source code and referenced in TypeInfo.type_name
//   string type_name = 1;
//   TBD serialized type specification. Might render "name" field unnecessary.
//   google.protobuf.Any type_spec = 2;
//}

message P4Info {
  repeated Extern externs = 1;
  repeated Table tables = 2;
  repeated Action actions = 3;
  repeated ActionProfile action_profiles = 4;
  repeated Counter counters = 5;
  repeated DirectCounter direct_counters = 6;
  repeated Meter meters = 7;
  repeated DirectMeter direct_meters = 8;
  repeated ControllerPacketMetadata controller_packet_metadata = 9;
  // Top-level package documentation, i.e. for the forwarding pipeline config
  PkgInfo pkg_info = 10; // [chris] This probably should be first element
  // Future? List of data types referenced by TypeInfo
  // Types types - 11;
}
```

**Comment by antoninbas** [comment]
It seems that the `type` keyword in P4_16 is the way to go for this.
