### ISSUE TITLE
Port Translation

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/PI#284]
Opening this issue to track P4Runtime spec changes for handling port translation. This issue was discussed in the API WG on Dec 13. Here is a synopsis:

1. PSA defines vendor specific PortId_t for hardware ports. SDN controllers, talking to multiple vendor switches, may have a separate, global 16/32/64 bit space of port values. So, P4 runtime should provide a mechanism for translation between controller port values and vendor-specific HW port values in match fields, action parameters and packet-io controller metadata.

2. Proposal is to support a special P4Runtime annotation @port_translation("controller_port_bitwidth : <W>"), where W is the controller port bitwidth. The port translation tables are expected to be part of the switch config.

3. Potentially support automatic annotation of all match fields, action parameters and packet-io controller metadata of PortId_t type using a single annotation on the top-level package.

**Comment by antoninbas** [comment]
Done in https://github.com/p4lang/p4runtime
