### ISSUE TITLE
P4 info read/serialize functions don't process match field annotations

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/PI#285]
The p4info.proto definition declares that matchfields convey annotations:

```
message MatchField {
  uint32 id = 1;
  string name = 2;
  repeated string annotations = 3;
```

However the code for reading or serializing match field annotations seems to be absent for all formats (native, protobuf, bmv2). This annotation info could be very useful for control-plane code and interface generation.

**Comment by antoninbas** [comment]
Chris, sorry for the delay in replying. If I am understanding your issue correctly, you are referring to the fact that P4Info annotations are not read & stored in the in-memory `pi_p4info_t` C struct which is used by the PI C library? In turn this means that the "native" serialization format is missing these annotations.

First, I would like to deprecate the "native" format for p4info. It pre-dates the protobuf version of P4Info and I cannot really justify keeping it around any more. Software - whether on the client side or server side - that do not wish to link with the protobuf library can use the JSON serialization of the P4Info message (which can be produced by the compiler with `--p4runtime-format json`).

Regarding the in-memory `pi_p4info_t` structure. It is only meant to be consumed by vendors which have chosen to implement the PI C stubs in-order to support P4 Runtime (therefore avoiding to have to implement the gRPC P4Runtime service themselves). Few people are using it and until now, no one using `pi_p4info_t` has expressed interest in being able to access the annotations from `pi_p4info_t`. But maybe you are using `pi_p4info_t` now and you have a need for these annotations?

On a side-note I do not see PI and P4 Runtime as being on the same level. The P4 Runtime API is really community-driven while I have written the PI C library in a way that works well for me and the targets I have to support (I wouldn't quite call it a bottom->top design but...). PI may be a viable server-side implementation for more than 1 vendor, but client-code should definitely sick with the protobuf P4Info IMO (and stay away from `pi_p4info_t`).

Regarding the specific case of the bmv2 JSON, I think there is no need to have a generic way to represent annotations there. If an annotation is relevant to the bmv2 dataplane, the compiler will process it and there will probably be a dedicated JSON attribute for it. I remember writing some code to propagate P4_14 pragmas (the ancestor of P4_16 annotations) to the bmv2 JSON, but that was back when most people were using P4_14 and the p4lang/p4c compiler backend wasn't able to generate P4Info.

It's a long answer and it's possible that I completely misunderstood your question :)

**Comment by chrispsommers** [comment]
I realize that using the PI utilities is probably not the right way to go for writing P4 Info transforms and will pursue a different tactic, e.g. manipulating/processing the proto buffers directly in c++ or python. Still, adding the missing annotations to pi_p4info_t  might be useful someday.
