### ISSUE TITLE
Document behavior when notifications are generated too fast for control-plane

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#289]
1. HW can generate notifications too fast for P4 Runtime agent / server
2. P4 Runtime agent / server can generate notifications too fast for P4 Runtime client, in which case writes on the `StreamChannel` will block.

We need to emphasize that notifications can be lost and specify expected implementation behavior for each notification type. For example:
- packet-in: nothing to do, network will recover
- idle timeout: send a notification again after a second timeout period etc. to avoid dangling stale entries (does using an exponential backoff makes any sense here?)
- digest: send a notification again if learning event happens again (after some timeout?)

In addition, should we support some configurable rate-limiting for each notification type or is it an overkill?

@jafingerhut suggested that we should have a (optional?) drop count mechanism to count the number of dropped notifications.

**Comment by jafingerhut** [comment]
Regarding configurable rate-limiting for each notification type, it is possible in a P4 program to use a meter to decide whether to generate a digest message, or a packet to the control plane.  That would provide a configurable rate for such messages, albeit one that the control plane would need to know which meter instance name controlled these actions.

**Comment by antoninbas** [comment]
I'm pretty happy with the state of the current specification. We can open a new issue on https://github.com/p4lang/p4runtime if we find something is missing.
