### ISSUE TITLE
Make sure that P4 Runtime can be easily extended for non-PSA architectures

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#301]
A few TODO items that I'm aware of:
1. Read / Write support for arbitrary architecture-specific externs. There is already some basic support but that hasn't been tested with a concrete architecture.
2. Support additional match types. This was proposed by @jtardo here (https://github.com/p4lang/PI/issues/241#issuecomment-347966628).
3. Ability to extend `TableEntry` message with a `proto.Any` message field. That will provide support for architecture-specific runtime table properties and provide support for architecture-specific direct resources.
4. Support for different types of notifications on bi-directional stream.

As mentioned above we already have some tentative - and undocumented - support for 1. in p4runtime.proto and p4info.proto. I also have a few ideas for 2. and 3. For now I am just opening this issue to make sure it makes it to the roadmap for v1.0.

**Comment by hesingh** [comment]
A table used by a non-PSA architecture is a good candidate to test PI externs with.  I have provided an example below which serves as a good test table to test PI code with.  thanks.

table FwdTable {
        asic_tblprop1 = 72;
        size = 262144;
	asic_tblprop2 = 4;
	asic_tblprop3 = 1;
	asic_tblprop4 = false;
        key = {
	    struct_foo.Da         : exact; // Da
	    struct_foo.bd         : exact;
	    struct_foo.key_type   : exact;
        }
        actions = {processFwdTbl; processFwdTblMiss;}
        default_action = processFwdTblMiss;
        implementation = hash_table(6);
	properties = FwdTbl_properties;
    }

**Comment by antoninbas** [comment]
@hesingh Thanks for your comment. The example you give does not concern externs directly IMO (bullet point 1) but is an example of `TableEntry` extension (bullet point 3).
