### ISSUE TITLE
Is doing a TableEntry INSERT several times for a default entry an error?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#306]
Should default entries be treated like regular match entries in this respect? In this case the client would need to use INSERT when setting the default entry for the first time and MODIFY thereafter.

What's the expected behavior when the default entry is provided in the P4 program (not const)? Should INSERT always return an error in this case?

It seems that we have quite a few questions to answer regarding how the P4Runtime agent is supposed to handle entries (immutable match entries + default entries) provided in the P4 program.

**Comment by antoninbas** [comment]
@wmohsin @samar-abdi @aghaffarkhah any thoughts?

**Comment by samar-abdi** [comment]
For direct tables, I think the default entry is always implicitly present, so you can only MODIFY it if it is non const. For tables with extern (eg. selector) implementation, the default entry is NoAction and immutable.

**Comment by samar-abdi** [comment]
Perhaps, we should also add this in PSA, particularly the last point? What do you think @jafingerhut ?

**Comment by antoninbas** [comment]
I personally don't think PSA should have this restriction. IMO this is really a restriction we are adding in P4Runtime v1.0 to simplify implementations, which don't have to deal with default entries for indirect tables.

**Comment by jafingerhut** [comment]
I do not have a clear enough mental model of the detailed corner cases around action profiles and action selectors, and how those corner cases might differ across P4 implementations, to have an informed opinion here (at least not yet).  I get the uneasy feeling every time these kinds of corner cases arise in discussion in a P4 working group meeting, different people have different mental models of how these kinds of tables work, at least in the corners.

**Comment by antoninbas** [comment]
https://github.com/p4lang/PI/issues/306#issuecomment-386371513 was added to the spec so I'm closing this
We can create a new issue for more specific concerns around https://github.com/p4lang/PI/issues/306#issuecomment-386471264
