### ISSUE TITLE
How to do a wildcard Read on an indirect counter / meter?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#309]
This is the current p4runtime.proto message to run an entry in an indirect counter?
```
message CounterEntry {
  uint32 counter_id = 1;
  int64 index = 2;
  CounterData data = 3;
}
```
How to disambiguate between reading the counter at index 0 and reading all indices? Usually we leave the field unset to indicate a wildcard Read, but here it doesn't work if 0 is a valid index.

**Comment by samar-abdi** [comment]
Simple solution would be to wrap the index in a sub-message. Same for meters. If cell is omitted in a read request, then read all cells. Writes must specify cell.

message CounterEntry {
  message Cell {
      int64 index = 1;
  }
  uint32 counter_id = 1;
  Cell cell = 2;
  CounterData data = 3;
}

**Comment by antoninbas** [comment]
Decision at the 02/21/2018 WG meeting was to go with what @samar-abdi proposed and wrap index in a protobuf message (probably top-level since it will be used by counters, meters, registers and possibly other arch-specific externs).

**Comment by antoninbas** [comment]
@samar-abdi I opened a PR for this as I wanted to start implementing wildcard read properly. It also required changes to the P4Runtime service implementation and I wanted to make sure these were done in the same PR (otherwise the Travis CI would have failed).
