### ISSUE TITLE
Add more details regarding action parameters

### ISSUE THREAD

**Issue by teverman** [p4lang/PI#313]
p4runtime.md currently imposes the following constraints on action parameters:

for (auto param: action.param())
  assert(param.has_value())

This loop appears to apply only to action parameters that are present in TableEntry.action.params().  It does not prohibit leaving out action parameters.  If this is the intention, then what is the behavior for missing action parameters? Do they get some default value?  Is it OK to omit unused parameters?  Are unused parameters optional, all others required?

**Comment by antoninbas** [comment]
Added to the spec
