### ISSUE TITLE
How to add set_queue_rate and set_queue_depth in simple_switch_grpc?

### ISSUE THREAD

**Issue by coolvikas** [p4lang/PI#333]
I am new to p4Runtime, I am able to push table entries and p4 json to the switches using p4Runtime but how do I configure the simple_switch_grpc for set_queue_rate and set_queue_depth to implement rate limiting? Previously simple_switch_CLI supports set_queue_rate so I can configure it directly by simply writing it in s1-commands.txt file.

**Comment by antoninbas** [comment]
This can be done by enabling the Thrift server for simple_switch_grpc and using the simple_switch_CLI: https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc#enabling-the-thrift-server. However, when using P4Runtime, do not use simple_switch_CLI to modify state of P4 objects or you may end up with an inconsistent state in the P4Runtime server.

**Comment by coolvikas** [comment]
I have tried to compile simple_switch_grpc by enabling --with-thrift option but it fails to make. I have opened an github issue for the same here https://github.com/p4lang/behavioral-model/issues/574
