### ISSUE TITLE
git problem

### ISSUE THREAD

**Issue by jw1park** [p4lang/PI#334]
Hi. I am installing p4lang/PI on my notebook.
There are some problems.
It is git problem. 

When I enter "git submodule update --init --recursive" command,
It doesn.t work.

I just see this message.
fatal: Not a git repository(or any of the parent directories): .git

How do I do??

**Comment by chrispsommers** [comment]
Be sure to enter the **PI** directory created by your initial `git clone` command, before you do the `git submodule update` command,

**Comment by antoninbas** [comment]
Closing this since there was no update and Chris probably gave the right solution for this.
