### ISSUE TITLE
TableEntry.match semantics for ternary (don't care) match fields

### ISSUE THREAD

**Issue by wmohsin** [p4lang/PI#35]
message TableEntry {
  ...
  repeated FieldMatch match = 2;
  ...
}

For a table entry that would like to specify "don't care" values for some of the ternary match fields, we propose the following semantics:
"If a 'match' field has type TERNARY and a value is not provided in a table insert/modify operation, the value will be set to 0 with a 0 mask (i.e. dont care)"

**Comment by antoninbas** [comment]
The current specification (https://github.com/p4lang/PI/blob/master/proto/docs/p4runtime.md#tableentrymatch-fieldmatchfield_id-and-other-fields-of-the-fieldmatch) states that in the case of ternary match fields, the client MAY omit the `match`, which translates as "don't care". This is semantically equivalent to providing a `match` with both `value` and `mask` set to 0. The current implementation supports both but may return a semantically-equivalent - but different - representation when the client does a `Read` RPC.

Should we take one of the following steps:
1) Agree on a canonical representation of ternary matches. For example, require that the `match` be omitted for "don't care" (which means `mask` would never be allowed to be 0).
2) Require that P4Runtime implementations return the exact same message in `Read` RPCs as was sent in the corresponding `Write`?

**Comment by antoninbas** [comment]
The decision at the 24/01/2018 WG meeting was to go with (1.) and make the empty match field the canonical representation. An INVALID_ARGUMENT error code will be returned if the client uses a mask of 0s.

This issue will be closed once changes are made to the spec and the server code.
