### ISSUE TITLE
Question: How to read and write registers through P4Runtime?

### ISSUE THREAD

**Issue by VerricDr** [p4lang/PI#354]
Hi all,
     I want to read registers through P4Runtime.
My code:
control MyIngressImpl(...) {
      register<bit<32>>(100) reg;
      .....
}
Then generate P4Info file.
p4c xxx.p4 --std p4-16 --p4runtime-format text --p4runtime-file yyy.txt
The generated file doesn't contain any regsiter info. I think it should contains a regsiter info, especially id. I also tried counter, it will successfully generate counter info in P4Info file.

**Comment by antoninbas** [comment]
Support for generating register information in P4Info was added to the compiler very recently, so I suggest you update your compiler by pulling the latest master branch.

However, the P4Runtime reference implementation does NOT include support for registers yet (https://github.com/p4lang/PI/blob/master/proto/frontend/src/device_mgr.cpp#L1340), so even though you can generate the correct P4Info, you will not be able to read & write registers through P4Runtime (you will get back an `UNIMPLEMENTED` error code).

**Comment by VerricDr** [comment]
Thanks
