### ISSUE TITLE
Remove max_size from ActionProfileGroup message in P4Runtime

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/PI#361]
The max size refers to the max number of members per group.  This is a static property of the action selector instance, not a runtime programmable field.

**Comment by antoninbas** [comment]
Decision at the 05/30/2018 WG meeting was to keep the field and make it optional. If the client doesn't set the field (default value is 0), the server defaults to the static max size defined in P4 program (and soon to be part of P4Info: #366)
