### ISSUE TITLE
Should there be a 'sync' option for write requests?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#375]
Maybe this has already been discussed and I've missed it.  Feel free to point me at appropriate documentation or options in the proto definition of P4Runtime if so.

The semantics I think defined today for batch write requests is "individual operations can be done in any order, but all in one write batch must be committed to the data plane before any operations in a later write batch are committed to the data plane".  That gives strong ordering requirements between write batches, but I don't think it actually says anything that lets a P4Runtime client know that _now_ my writes have been committed to the data plane.  For example, a P4Runtime client could just store the write batch contents in memory, checking them enough to know that they will succeed, but not actually writing them to the data plane yet, and acknowledge them back to the client.

If that is true, then I can imagine there may be times that a client will want to know that all of their writes have finished being written to the data plane.  One way would be to have a 'sync' command that only returns success when all previous writes are committed to the data plane.  Another would be to have a 'sync' flag on the existing write commands, which a client can set to false when they don't care to wait until the writes are committed to the data plane, or true when they do care to wait until that time.

Example when a client might care -- they want writes to one network device to be completely committed, before beginning writes to a different network device.

**Comment by antoninbas** [comment]
My understanding is that the Write RPC is synchronous in the sense that it only returns when all writes have been committed to the dataplane.
This is also what @wmohsin wrote in the spec:

> When the Write RPC returns, it is required that all operations in the batch have been committed to hardware (P4 data plane).

**Comment by jafingerhut** [comment]
Got it, and makes sense.  Closing this issue.
