### ISSUE TITLE
Inconsistency of parameter interpretation

### ISSUE THREAD

**Issue by nerudaj** [p4lang/PI#382]
When using the CLI and executing command such as this:
PI CLI> table_add ipv4_lpm 10.0.0.1/24 => set_nhop 10.0.0.1 42
the values send to RPC methods are not consistently interpreted.

While the IP address parameter of the set_nhop action is interpreted as a sequence of decimal bytes: 10 0 0 1, the
port number is interpreted as a sequence of hexadecimal bytes: 0x42 0x00. Is this an intended behaviour? Are all parameters interpreted as hexa numbers with the exception of the IP addresses or are there more exceptions?

**Comment by antoninbas** [comment]
This is just for the sake of convenience. If I'm not mistaken, you are free to provide the IP address as an hexadecimal string as well:
```
PI CLI> table_add ipv4_lpm 0x0a000001/24 => set_nhop 0x0a000001 42
```

**Comment by nerudaj** [comment]
Thanks for clarification. It would be great if that was explained in the main readme with CLI usage example.
