### ISSUE TITLE
--with-bmv2 does not work 

### ISSUE THREAD

**Issue by shouxi** [p4lang/PI#389]
Hi, 
Does PI support `--with-bmv2`?

After configuring PI with `./configure --with-bmv2 --with-proto`, I encounter the following compile error on `make`: 
![image](https://user-images.githubusercontent.com/1788789/42136072-b013f174-7d87-11e8-85dd-69304a8d0572.png)

I notice that the header file of `boost::shared_ptr` is not included in  `conn_mgr.cpp`. 
So, I add `#include <boost/shared_ptr.hpp>` in the file  but then get a new error:
![image](https://user-images.githubusercontent.com/1788789/42136166-1c7f0aaa-7d89-11e8-8d0a-c0bd1f687b8e.png)

Thanks

**Comment by antoninbas** [comment]
I've seen this error before when the Thrift version installed wasn't one of the supported versions (0.9.2, 0.9.3)

**Comment by antoninbas** [comment]
It seems that there is a submitted patch to make it work with more recent versions of Thrift (https://github.com/p4lang/PI/pull/373) but I didn't get a reply to my comment on this PR yet.

**Comment by shouxi** [comment]
You are right.  After downgrading from thrift 0.11.0 to 0.9.3, it works! Thanks a lot.
