### ISSUE TITLE
Nested Structures

### ISSUE THREAD

**Issue by hesingh** [p4lang/PI#395]
In section 8.5.2 of the P4Runtime specification, I see how complex P4 types are supported.  I would like to know how would a nested bit-vector struct be supported?

**Comment by antoninbas** [comment]
This would be more relevant to the P4Runtime repo: https://github.com/p4lang/p4runtime
All types which are currently supported in P4 should also be supported in P4Runtime. The `P4DataTypeSpec` protobuf message (https://github.com/p4lang/p4runtime/blob/master/proto/p4/config/v1/p4types.proto#L63) is used to **describe** P4 types and supports nesting. If by "nested bit-vector" you mean nested structs, then this is supported. Header types can only include bit string fields, as per the P4 spec.
The `P4Data` message is used to **provide values** as per the corresponding `P4DataTypeSpec` instance (https://github.com/p4lang/p4runtime/blob/master/proto/p4/v1/p4data.proto#L19). Note that in P4Runtime v1.0 we made the decision to not use `P4Data` for action parameters and match key fields, which are restricted to bit strings.

**Comment by hesingh** [comment]
Yes, I do mean "nested bit-vector"  as nested structs. Great to hear nested structs are supported!  Yes, I do recall, P4Runtime v1.0 does not support P4Data for action parameters.  Thanks much for replying.
