### ISSUE TITLE
Will the P4Runtime support psa_switch?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/PI#402]
Will the P4Runtime support the `psa_switch` target? Is there any plan? Thanks.

**Comment by hesingh** [comment]
P4Runtime does support PSA and v1model switches

**Comment by dingrui37** [comment]
My expression may not be accurate. In fact, I want to ask if the target `psa-switch` will support P4Runtime, like `simple_switch_grpc` target.
https://github.com/p4lang/behavioral-model/tree/master/targets/psa_switch

**Comment by antoninbas** [comment]
It will eventually, but not until more progress is done on the P4 implementation, both at the compiler level and at the bmv2 level.

**Comment by dingrui37** [comment]
Thanks @antoninbas @hesingh
