### ISSUE TITLE
Support "oneshot" action selector programming in P4Runtime implementation

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#405]

**Comment by jafingerhut** [comment]
@konne-google The OneShot update will include a mapping like key -> {set of (action name + action parameters)}, with all action names restricted to be the same for now perhaps to live within PSA data plane restrictions.

The desired behavior is probably 'atomic' in the sense that for every packet applying that table should either get the original before-update action, or the new after-update action, never something else?

If so, I guess the implementation should create a new unused action selector group, add the members to it, and only when that is complete it should change the table entry to make the key point at that new group, then it should delete the old members and group if they are not pointed at by any other key?

In general, the only time two keys could share a group is if the implementation chose to check whether the "set of (action name + action parameters)" is identical for two keys, and reuse the same group in that case?  That seems like a special enough case that maybe it shouldn't be required behavior that a P4Runtime server needs to check for it to try and take advantage of it.

**Comment by konne-google** [comment]
I agree, that it'll likely be easiest to generate the members first, then add the group, and finally add the table entry (do the reverse for deletes), but I'm happy with any implementation that works :)

There's no requirement for any deduplication optimization, but an implementation is free to do it if it wants.
