### ISSUE TITLE
simple_switch_grpc allows setting a table's default action to an action with @tableonly attribute

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#416]
If this issue belong in a different repo (e.g. p4lang/behavioral-model), please let me know and I will close this one and create a new one there.

This was done using Python bindings of the P4Runtime API over gRPC.

I have tested this with about a 1-week-old version of p4lang/p4c, behavioral-model, p4runtime, and PI repositories, so if things have changed since then, let me know and I will update.

From my reading of the P4_16 spec, actions with the @tableonly attribute should be rejected if the control plane attempts to set such an action as a table's default action.

I have also seen simple_switch_grpc allow adding a table entry with an action that has the @defaultonly attribute, which similarly seems like it ought to cause an error.

**Comment by antoninbas** [comment]
Let's make this change to the spec first (https://github.com/p4lang/p4runtime/issues/83) and then it can be implemented in the P4Runtime implementation used in simple_switch_grpc.

In theory we can also make sure it's included in the bmv2 JSON and enforce "@defaultonly" and "@tableonly" in bmv2 directly, but I'd rather do it in this repo. I'll be able to return a better error code / message as well (there is no good way to propagate bmv2 errors to P4Runtime at the moment, so we always get a very generic error).

**Comment by jafingerhut** [comment]
@antoninbas Thanks for all of the changes you've now merged in.  I plan to do at least a very basic test of them soon.

It seems that the basic idea of the changes is as follows.  Let me know if you see anything inaccurate here:
+ p4c will now add new information to the P4Info file it generates (if p4c is invoked with arguments to generate such a file) that indicate for each table action whether it is tableonly, defaultonly, or "either use of this action is legal"
+ simple_switch_grpc will reject attempts to add or modify a table entry marked defaultonly, returning an error code back to a P4Runtime client/controller that attempts this.  Similarly if the controller attempts to modify a default action of a table to an action marked tableonly.  This is the one I am less sure about -- is there checking in the simple_switch_grpc process itself, or do the changes made up to now only include checking in the low level P4Runtime code running on the client/controller?

Thanks,
Andy

**Comment by antoninbas** [comment]
The checks happen in the simple_switch_grpc process, but they are implemented in this repo (in the server code): https://github.com/p4lang/PI/blob/master/proto/frontend/src/device_mgr.cpp#L2186
