### ISSUE TITLE
MasterArbitrationUpdate not working after PI update

### ISSUE THREAD

**Issue by endrigoshi** [p4lang/PI#417]
Hi all,
In another issue opened I noticed that @antoninbas mentioned that the tutorials do not work with the newest code of the P4Runtime. And indeed after updating my code I get 

> gRPC Error  (UNIMPLEMENTED) 

right from the beginning. However I am new to P4 and P4Runtime and I was using the tutorial code as a reference to building my application. Hence, I would really appreciate if someone can guide me through the necessary code modifications to successfully send e.g. MasterArbitrationUpdate to the switch.
If it can be explained by changing the code provided in the tutorial file switch.py I would be more than grateful.

    def MasterArbitrationUpdate(self, dry_run=False, **kwargs):

        request = p4runtime_pb2.StreamMessageRequest()
        request.arbitration.device_id = self.device_id
        request.arbitration.election_id.high = 0
        request.arbitration.election_id.low = 1

        if dry_run:
            print "P4Runtime MasterArbitrationUpdate: ", request
        else:
            self.requests_stream.put(request)
            for item in self.stream_msg_resp:
                return item

As for my environment, except for the P4Runtime code that I updated, the others are the same used for the tutorials VM.

**Comment by antoninbas** [comment]
An `UNIMPLEMENTED` error like this without a message is unlikely to be returned by the latest P4Runtime code. It would be returned if you are actually running a different gRPC service (not P4Runtime) on the provided port.

**Comment by endrigoshi** [comment]
Hi @antoninbas !
I managed to fix the error. After updating to the latest code, it was necessary to import `p4runtime_pb2` from `p4.v1` instead from `p4` as it was before in the tutorial. Also it was necessary to comment lines 100-103 in the `hepler.py` file provided in the tutorials. I don't know if this is the correct approach but this is what worked for me.

**Comment by rs556655** [comment]
> Hi @antoninbas !
> I managed to fix the error. After updating to the latest code, it was necessary to import `p4runtime_pb2` from `p4.v1` instead from `p4` as it was before in the tutorial. Also it was necessary to comment lines 100-103 in the `hepler.py` file provided in the tutorials. I don't know if this is the correct approach but this is what worked for me.

I modified line 100 in `helper.py` to   `if match_type == p4info_pb2.MatchField.UNSPECIFIED:`.
