### ISSUE TITLE
grpc_demo controller problem

### ISSUE THREAD

**Issue by LiPeio-o** [p4lang/PI#425]
hello, I have encountered a problem when i run the grpc_demo.  I can correctly run the command  `sudo python 1sw_demo.py --json simple_router.json --cpu-port veth250`   and   `sudo ./pi_grpc_server`,
but when I run `sudo ./controller -c simple_router.json`, it return failed like this:

> lt-controller: simple_router_mgr.cpp:274: int SimpleRouterMgr::assign(const string&, const string*): Assertion `status.ok()' failed.
Aborted (core dumped)

so, how can i deal with it ... thx a lot

**Comment by antoninbas** [comment]
I tried with the latest bmv2 software and PI software and just followed the README instructions, and the demo was working fine.
Maybe one of the other processes is printing an error message (e.g. `pi_grpc_server`). In any case, I am adding an additional log message that may be helpful: https://github.com/p4lang/PI/pull/426

**Comment by antoninbas** [comment]
Closing this since no update
