### ISSUE TITLE
P4 visualizer

### ISSUE THREAD

**Issue by Nic30** [p4lang/PI#431]
Hello,

is there any data-flow visualizer for P4 language?

I do have some [visualizer](https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.logic.crcComb.CrcComb-4.json) for hardware circuits. I would like to rewrite it to support FIRRTL language and maybe others. It seems to me that it maybe nice to have visualizer for P4. Do you think that such a tool would be useful for you?

(
Input of visualizer is simple JSON I do ask if I should add shapes for P4 entities and extend some existing P4 compiler to generate suitable JSON for visualization.
)

**Comment by antoninbas** [comment]
I don't think this is the right place to bring this up. This repository is a reference P4Runtime implementation. Maybe you should consider bringing this up in the p4c repo (P4 compiler) or better still through the p4-dev mailing list.

**Comment by Nic30** [comment]
Anyway there already is such a tool https://github.com/IITH-Compilers/P4LLVM/tree/master/backends/graphs
