### ISSUE TITLE
PI build error: recipe for target 'pi_server_dummy' failed

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/PI#433]
I've built this in the past (a year ago). Made a new clone and followed instructions, get a build error.`
```
./configure --with-proto --without-internal-rpc --without-cli
make
```
Making all in demo_grpc
make[4]: Entering directory '/home/chris/p4lang/PI/proto/demo_grpc'
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -Wall -Werror -Wno-unused-command-line-argument -g -O2 -std=c++11   -o pi_server_dummy pi_server_main.o ../server/libpigrpcserver.la ../frontend/libpifeproto.la ../libpiprotogrpc.la ../libpiprotobuf.la ../../src/libpiall.la ../../targets/dummy/libpi_dummy.la -lmicrohttpd 
libtool: link: g++ -Wall -Werror -Wno-unused-command-line-argument -g -O2 -std=c++11 -o .libs/pi_server_dummy pi_server_main.o  ../server/.libs/libpigrpcserver.so ../frontend/.libs/libpifeproto.so ../.libs/libpiprotogrpc.so ../.libs/libpiprotobuf.so ../../src/.libs/libpiall.so ../../targets/dummy/.libs/libpi_dummy.so -lmicrohttpd -pthread
../frontend/.libs/libpifeproto.so: undefined reference to `pi::ActProf::group_set_members(unsigned long, unsigned long, unsigned long const*)'
../frontend/.libs/libpifeproto.so: undefined reference to `pi::MatchTable::default_entry_reset()'
../frontend/.libs/libpifeproto.so: undefined reference to `pi::MatchKey::set_is_default(bool)'
collect2: error: ld returned 1 exit status
Makefile:528: recipe for target 'pi_server_dummy' failed

**Comment by antoninbas** [comment]
I wasn't able to reproduce this on my VM, nor in a fresh docker container.
These "missing" symbols are new functions that have been introduced at different points during the last couple of months. So a fair guess would be that a stale version of some library is being used. But you do mention that you started from a fresh clone and all  the libraries should be picked up locally. This is an issue I usually experiment during the compilation phase with some state header files being picked up in system directories, if the Makefile are not completely correct. However I have never had this issue with libraries. Just in case you may want to make sure you don't have older versions of the PI libraries installed (the particular library where these symbols are defined is libpifecpp).
It could be useful to have the output of `ldd ../frontend/.libs/libpifeproto.so`  as well. It should link against the local version of libpifecpp. You can then check that the symbols are correctly defined in that library. In my case:
```
antonin@ubuntu:~/Documents/p4lang/PI/proto/demo_grpc$ ldd ../frontend/.libs/libpifeproto.so
	linux-vdso.so.1 =>  (0x00007ffe19160000)
	libpifecpp.so.0 => /home/antonin/Documents/p4lang/PI/frontends_extra/cpp/.libs/libpifecpp.so.0 (0x00007f32f3eb1000)
	libpiconvertproto.so.0 => /home/antonin/Documents/p4lang/PI/proto/p4info/.libs/libpiconvertproto.so.0 (0x00007f32f3c80000)
	libpiprotobuf.so.0 => /home/antonin/Documents/p4lang/PI/proto/.libs/libpiprotobuf.so.0 (0x00007f32f3605000)
	libpip4info.so.0 => /home/antonin/Documents/p4lang/PI/src/.libs/libpip4info.so.0 (0x00007f32f33eb000)
	libboost_thread.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 (0x00007f32f31c5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f32f2e43000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f32f2a79000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f32f44ce000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f32f2863000)
	libprotobuf.so.12 => /usr/local/lib/libprotobuf.so.12 (0x00007f32f241b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f32f2112000)
	libJudy.so.1 => /usr/lib/x86_64-linux-gnu/libJudy.so.1 (0x00007f32f1ec1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f32f1ca4000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f32f1aa0000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f32f1898000)
```
```
antonin@ubuntu:~/Documents/p4lang/PI/proto/demo_grpc$ nm /home/antonin/Documents/p4lang/PI/frontends_extra/cpp/.libs/libpifecpp.so.0 | grep group_set_members
0000000000008a9e T _ZN2pi7ActProf17group_set_membersEmmPKm
```

**Comment by antoninbas** [comment]
That is surprising because the makefiles always link to the libtool libraries (.la files) and use the exact path to the library to do so. But it is not that crazy that LD_LIBRARY_PATH would get picked up here. We are linking to `../frontend/.libs/libpifeproto.so` which is correct. I would expect `libpifeproto.so` to use the local version of `libpifecpp.so`, but it makes sense that the linker would first lookup that library in LD_LIBRARY_PATH. I don't think there is anything to "fix" in the build system. The risks of exporting LD_LIBRARY_PATH I guess :)
