### ISSUE TITLE
Miscellaneous minor tools to develop for PI 

### ISSUE THREAD

**Issue by hesingh** [p4lang/PI#445]
I am using p4c/tools/cpplint.py to lint PI code changes to a .cpp file.   Maybe, PI can develop its own.

p4c supports a LOG utility.  PI does not and should add it. 

Investigate 'operator<<' overload to print data structures in PI code that is not protobuf-related.  Protobuf knows how to print its data structs.

**Comment by antoninbas** [comment]
There is already a lint tool in this repo: https://github.com/p4lang/PI#contributing

**Comment by hesingh** [comment]
Duh, now I recall it.  Sorry, I missed it - thanks!
