### ISSUE TITLE
Support canonical bytestring representation in P4Runtime implementation

### ISSUE THREAD

**Issue by antoninbas** [p4lang/PI#454]
See https://s3-us-west-2.amazonaws.com/p4runtime/docs/v1.0.0/P4Runtime-Spec.html#sec-bytestrings. The implementation currently requires bytestrings to be 0-padded to the "correct: length (the bitwidth of the P4 type).

**Comment by konne88** [comment]
Is there a plan to implement this? Right now we need to always convert table entries to the wrong format before we send them to BMv2.

**Comment by antoninbas** [comment]
I may be able to get to it some time this month. But if someone else wants to take a stab at it, I would welcome it. I believe this should be a pretty straightforward task, and the largest effort will be making sure that Entities in ReadResponses use the canonical bytestring representation.

**Comment by konne88** [comment]
This is awesome Antonin, thank you!

**Comment by smolkaj** [comment]
Sweet, thanks!
