### ISSUE TITLE
Python protobuf / grpc files are not installed correctly.

### ISSUE THREAD

**Issue by Pfeifenjoy** [p4lang/PI#458]
I have installed PI by compiling it and running make install.

My default python version is python3.7, however I also have installed python2.7.
When I run `make install` the p4.v1 etc. files are installed under `/usr/local/lib/python3.7/site-packages` and not under the appropriate python2.7 directory.

I have tried to fix this issue by moving the p4 folder to the python2.7 directory.
However then I encounter an attribute error:

`AttributeError: 'module' object has no attribute 'P4RuntimeStub'`

when I want to access `p4runtime_pb2.P4RuntimeStub`.

Does anybody know why this is happening and how I can fix it?

**Comment by hesingh** [comment]
I haven't see Python 3 and Python 2 working well together on a machine.  I'd remove python 3 if you want to work with PI.  Both PI and p4c use Python 2. If you don't mind removing your PI source, please do so and use Andy's script to install PI and all that it needs.

https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-p4runtime.sh

**Comment by antoninbas** [comment]
* I believe you can manually set the `PYTHON` environment variable when running `./configure` to force autotools to use a specific version: `PYTHON=python2 ./configure <other flags>`.

* In more recent versions of Protobuf / gRPC, `P4RuntimeStub` is no longer in `p4runtime_pb2.py` but is in `p4runtime_pb2_grpc.py`. You should import `p4runtime_pb2_grpc` in addition to `p4runtime_pb2`. Use `p4runtime_pb2` for messages and `p4runtime_pb2_grpc` for the service stub: `p4runtime_pb2_grpc.P4RuntimeStub`.

**Comment by Pfeifenjoy** [comment]
@antoninbas 
Thanks for your answer. Setting the PYTHON environment worked :+1: , however no p4runtime_pb2_grpc.py file is generated.
Which is kind of weird since on another laptop of mine this works with not the same grpc version, but a relatively knew one, where I also have to generate an extra grpc file.
It would also make sense to "concat" the p4runtime_pb2 and p4runtime_pb2_grpc
to ensure compatibility.

My guess is that somehow the grpc files are not generated.
Do I have to generate it manually?

**Comment by antoninbas** [comment]
Until a recent commit (https://github.com/p4lang/PI/commit/f80a2d5a8bb6ceef368930aee1dfd93c6e3af5f6) from March 18th, I wasn't installing p4runtime_pb2_grpc.py. So make sure you're using the latest version of this repo.

If you don't even see p4runtime_pb2.py being installed, I'm not sure how to help you, you can check out the build logs and see if there is anything suspicious there. Of course nothing will be generated / installed if you don't have the gRPC Python plugin installed at the time of running `./configure`.

The files used to be "concatenated" by the protoc compiler for a long time. This is no longer the case. I'm sure there have good reasons not to do it anymore, but I'm not familiar with them.

**Comment by Pfeifenjoy** [comment]
It worked.
