### ISSUE TITLE
Using last outside the parser.

### ISSUE THREAD

**Issue by santos-lucas** [p4lang/PI#463]
I was using last for a header_stack on p4_14 outside the parser, what by the specification should not be possible, but the code has compiled well, with no erros from the compiller, but i was gettin a error at the setup of the switch at mininet (probably because i was with a invalid code)... So, i think there is a bug in the compiler, because the code should't be copilled in the first place.

**Comment by jafingerhut** [comment]
If you want this to be improved in the compiler, the Github project for which you should create an issue is p4c: https://github.com/p4lang/p4c

This project is for the control plane API implementation.

**Comment by jafingerhut** [comment]
Also, I would recommend attaching a sample P4 program that exhibits the problem to whatever issue you create there, as it saves time for those who may enhance the compiler.
