### ISSUE TITLE
Cannot initialize DeviceMgr from a C code

### ISSUE THREAD

**Issue by osinstom** [p4lang/PI#512]
I'm trying to use PI library to implement P4Runtime in the [P4-OvS](https://github.com/osinstom/P4-OvS) project. I'm able to run gRPC server by using `PIGrpcServerRunAddr()`. However, SetForwardingPieplineConfig RPC fails, because `DeviceMgr` is not initialized. To fix that I would need to invoke `DeviceMgr::init()`, but it is not exposed via C API. 

According to discussion with Antonin, `DeviceMgr::init()` should be called by `PIGrpcServerRunAddr()` and `DeviceMgr::destroy` called by `PIGrpcServerCleanup`.

**Comment by antoninbas** [comment]
In the end I went with a new function, `PIGrpcServerInit`, which takes care of calling `DeviceMgr::init()`.
