### ISSUE TITLE
Deadlock possible in DeviceState

### ISSUE THREAD

**Issue by saynb** [p4lang/PI#523]
A deadlock is possible in a scenario where a controller is designed in a way where it doesn't keep emptying the StreamChannel. If a digest is sent by the server then [this](https://github.com/p4lang/PI/blob/master/proto/server/pi_server.cpp#L204) lock will be taken and not released till the controller side is read.
This can lead to a lock in processing usual Unary Write requests over [here](https://github.com/p4lang/PI/blob/master/proto/server/pi_server.cpp#L399) and in other similar places.

I couldn't find any literature regarding any recommended way of writing the controller implementation to process messages coming in on the StreamChannel.

**Comment by saynb** [comment]
One possible solution I can think of avoiding any dangling raw pointers of `Connection` object is by using `shared_ptrs` [here](https://github.com/p4lang/PI/blob/master/proto/server/pi_server.cpp#L344) and extending the lifetime of this connection object to at least the end of that API call so as to avoid dangling pointers.

**Comment by henli070** [comment]
I've ran into this issue in practice with the mac learning implementation in my controller.
How the controller works is that when it receives a digest, it tries to add a table entry in the same thread.

Usually this works fine, but if the P4Runtime server sends two digests quickly the dead lock occurs:
- The controller uses a single thread so it won't read from the stream again until it finishes adding the table entry.
- The P4Runtime server holds its lock while waiting for the 2nd digest to be read by the controller, so it can't add the table entry.

**Comment by antoninbas** [comment]
We could use a combination of these 2:
* switch to a RW mutex to protect the `DeviceState` - this will keep ensuring that we never write to an invalid stream object (the pointer becomes invalid after `StreamChannel` returns) while allowing concurrent access for `send_stream_message` and unary RPCs such as `Write`.
* add an extra mechanism to ensure sequential writes to the stream object: this can be a new mutex or a queue data structure. If we go with a queue (single consumer thread), we may increase the overhead but we will get some buffering which may benefit other parts of the system and we will get the ability to prioritize stream messages, e.g. we can prioritize arbitration updates over digests and prioritize digests over packet-ins.
