### ISSUE TITLE
Compile issue with Tofino SDE 9.3 (and 9.4)

### ISSUE THREAD

**Issue by egerpon** [p4lang/PI#535]
Hi,

Building of proto seems failing because it is not possible to specify the include directory where protobuf headers can be found.
Applying the small change below and specifying CXXFLAGS with proto/configure fixes the problem for me.
But I'm not entirely sure that I understand well your build system, so I didn't want to send in this patch as pull request.
Thanks if you fix it or if you tell me how to make it work by some other means.
BR,

Gergely

-------------------------

egerpon@barefoot:/p4sde/bf-sde-9.4.0/p4studio_build/third_party/PI$ git diff
diff --git a/proto/Makefile.am b/proto/Makefile.am
index 94616b2..77712bc 100644
--- a/proto/Makefile.am
+++ b/proto/Makefile.am
@@ -9,7 +9,7 @@ endif

 SUBDIRS = . third_party p4info frontend server $(MAYBE_PROTO_DEMO) tests

-PROTOFLAGS = -I$(abs_srcdir) -I$(abs_builddir)
+PROTOFLAGS = -I$(abs_srcdir) -I$(abs_builddir) $(CXXFLAGS)

**Comment by egerpon** [comment]
Sorry, wanted to say CPPFLAGS instead of CXXFLAGS

**Comment by hesingh** [comment]
Please contact Barefoot/Intel support for any Tofino issue,

**Comment by egerpon** [comment]
> Please contact Barefoot/Intel support for any Tofino issue,

Hi, sorry to say, but this doesn't seem to be a Tofino SDK issue - configure's cppflags simply doesn't seem to be used here for protoc, so I think with a default installation of protobuf (when you don't need to specify the include dir) it will surely work, but not in other cases. Am I completely wrong here? Maybe. Thanks!

Gergely

**Comment by jfingerh** [comment]
If you can reproduce the issue on a system with no Tofino SDE software on it, then please give the details of how to reproduce it.

If you can only reproduce the issue on a system with Tofino SDE software on it, then it is a Tofino-specific issue, and should be addressed elsewhere.
