### ISSUE TITLE
Do PacketOut messages still expect full byte width values, not canonical ones?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#545]
I believe I am running with the latest versions of PI, simple_switch_grpc, p4c, and tried out a test program using PacketOut messages from a Python PTF test using P4Runtime API, and I am not sure, but it seems like when I tried giving values to packet metadata fields using the canonical representation, it caused a packet to be injected into simple_switch that had the correct width for some 32-bit wide fields, but it appeared that there were some garbage data byte values in there if the 32-bit value I wanted to use for them were shorter than 4 bytes long when represented in canonical form.

I can provide a full test case if that is helpful for reproducing.

**Comment by jafingerhut** [comment]
Hmmm, now that I think about the behavior I am observing a bit more, it might be that this issue is specific to the code in p4lang/behavioral-model in simple_switch_grpc.  Not sure, though.

**Comment by hesingh** [comment]
Please provide test data.  I am interested - thanks,

**Comment by antoninbas** [comment]
@jafingerhut that sounds very likely (and this is indeed the right repository for this issue). It seems when I added support for canonical bytestrings, I forgot about Packet IO.

**Comment by jafingerhut** [comment]
If you want a small-ish test case, you can do this:
```
git clone https://github.com/jafingerhut/p4-guide
cd p4-guide
git checkout PI-issue-545
cd ptf-tests/packetinout
```
Then run the commands in the README.md file of that directory.

The test fails as the code is there, but by changing the code in Python method `encode_packet_out_metadata` of `testlib/base_test.py` to always encode integers as the full width in bytes of the metadata field, the test works.
