### ISSUE TITLE
Cannot compile gRPC

### ISSUE THREAD

**Issue by zyddnys** [p4lang/PI#550]
I was following the instruction on installing gRPC [here](https://github.com/p4lang/PI), however I got the following error:
```
In file included from /usr/include/string.h:495,
                 from third_party/cares/cares/setup_once.h:35,
                 from third_party/cares/cares/ares_setup.h:214,
                 from third_party/cares/cares/ares_parse_ptr_reply.c:17:
In function ‘strncpy’,
    inlined from ‘ares_parse_ptr_reply’ at third_party/cares/cares/ares_parse_ptr_reply.c:134:11:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/cares/cares/ares_parse_ptr_reply.c: In function ‘ares_parse_ptr_reply’:
third_party/cares/cares/ares_parse_ptr_reply.c:134:47: note: length computed here
  134 |           strncpy(aliases[aliascnt], rr_data, strlen(rr_data)+1);
      |                                               ^~~~~~~~~~~~~~~
third_party/cares/cares/ares_parse_ptr_reply.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
cc1: all warnings being treated as errors
make: *** [Makefile:2947: /home/unknown/p4/grpc/objs/opt/third_party/cares/cares/ares_parse_ptr_reply.o] Error 1
```

**Comment by zyddnys** [comment]
I fixed it by upgrading gRPC to v1.27.1 and following installation guide [here](https://grpc.io/docs/languages/cpp/quickstart/), but now I can't compile PI:
partial output of `./configure --with-bmv2 --with-proto --with-cli && make -j`:
```
In file included from ./PI/proto/util.h:26,
                 from src/util.cpp:21:
cpp_out/p4/config/v1/p4info.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
   17 | #error This file was generated by an older version of protoc which is
      |  ^~~~~
cpp_out/p4/config/v1/p4info.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
   18 | #error incompatible with your Protocol Buffer headers. Please
      |  ^~~~~
cpp_out/p4/config/v1/p4info.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
   19 | #error regenerate this file with a newer version of protoc.
      |  ^~~~~
```

**Comment by jafingerhut** [comment]
If you want to build p4lang/p4c, behavioral-model, PI, and a few other p4lang projects from source code, one way that I test (and fix, if it ever breaks) about once per month are a couple of scripts, linked from here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

The install-p4dev-v2.sh script mentioned there is the more well tested one, but requires starting from a freshly installed Ubuntu 18.04 system.

The install-p4dev-v4.sh script mentioned there is a little more experimental, in that it avoids installing Python2 completely, using only Python3 libraries, but it has succeeded for me on both freshly installed Ubuntu 18.04 or Ubuntu 20.04 systems.

**Comment by antoninbas** [comment]
The first error (https://github.com/p4lang/PI/issues/550#issue-893441083) may indicate that your compiler version is not compatible with the gRPC version you are trying to build.

The second error may indicate that your version of protoc doesn't match the version of your Protobuf headers. If the version is the same, is it possible that the files you are trying to build were generated by protoc before you upgraded to a new version? In that case, you could try running `make clean` followed by `make` again.

**Comment by zyddnys** [comment]
Thank you for the reply, I solved it by downgrading gcc from 10 to 6. I wonder if it is possible in the future for the project to use newer version of gRPC and protobuf.
