### ISSUE TITLE
Unable to include PI/p4info.h

### ISSUE THREAD

**Issue by gabrielgonzalezcampos** [p4lang/PI#551]
Hello,
I'm trying to install P4-OvS, and after following these steps : 
`sudo apt install -y libnanomsg-dev libprotobuf-dev protobuf-compiler protobuf-compiler-grpc  libgrpc++-dev libgrpc-dev libgc-dev
git clone https://github.com/p4lang/PI
cd PI
git checkout p4-ovs
git submodule update --init
./autogen.sh
./configure --prefix=/usr --with-proto --with-fe-cpp --with-cli --with-internal-rpc --with-gnu-ld
make
sudo make install`
After these steps, I start the instalation of P4-OvS but it fails due to: PI/p4info.h: No such file or directory
when it is included `#include <PI/p4info.h>`
I don't know how to fix it.
Many thanks.

**Comment by antoninbas** [comment]
It's not very easy to decipher the steps you shared. I also have no idea what `git checkout p4-ovs` is about, there is no `p4-ovs` branch in this repository. Additionally, the versions of the dependencies you installed from the package manager may not be compatible with this software; you'll notice that the README recommends using specific version of Protobuf, gRPC, etc.

I recommend that you ran the steps again with the correct versions of the dependencies, and look for errors in the output. If `make` and `make install` are successful, there is no reason for the `PI/p4info.h` header not to be installed.
