### ISSUE TITLE
Error python package installation path

### ISSUE THREAD

**Issue by doraeric** [p4lang/PI#564]
I found that it installed compiled protobuf python files to `/usr/local/lib/python3.x/site-packages` on my ubuntu, but the path is not the right default installation location for python packages. On debian-based linux, the packages should be installed to `dist-packages` [1].
I believe it is caused by automake, it sets [pythondir](https://www.gnu.org/software/automake/manual/html_node/Python.html#index-pythondir) to incorrect location, and the [Makefile](https://github.com/p4lang/PI/blob/771d5c46106f14f33777e70f39df2ae772cdfe17/proto/Makefile.am#L127) is using pythondir. I found other projects also have the same issue if they use automake [2].

I think the solution is to make it a standard python package and install through python or pip. I am sorry that I have no idea how to do this since I am not familiar with it. I have to move the files to correct place manually in order to make it usable now.

[1] [What's the difference between dist-packages and site-packages?](https://stackoverflow.com/questions/9387928/whats-the-difference-between-dist-packages-and-site-packages)
[2] [update python install makefiles to avoid forcing site-packages ](https://github.com/coreemu/core/commit/a674f5bf78506d8d03ef3935a3c03b8d575397e0)

**Comment by rst0git** [comment]
Hi @doraeric, `dist-packages` is specific to Ubuntu/Debian and PI should install correctly as debian package:

```bash
. /etc/os-release
echo "deb http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/home:p4lang.list
curl -L "http://download.opensuse.org/repositories/home:/p4lang/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
sudo apt-get update
sudo apt install p4lang-pi
```

There is also a [py3localpath.py](https://github.com/p4lang/tutorials/blob/deb6aceceb41fd9518440d7d003686b0dc4be9a5/vm-ubuntu-20.04/py3localpath.py) script in the tutorials repository that is used to addresses this problem.

**Comment by doraeric** [comment]
Thanks for your information!

I will try the apt method, hope it works for the tutorial environment.

**Comment by antoninbas** [comment]
Closing this since no update. Feel free to re-open if needed.
