### ISSUE TITLE
Fix compile warning without PI_LOG_ON

### ISSUE THREAD

**Issue by dpward** [p4lang/PI#565]
https://github.com/p4lang/PI/blob/66da143288d4f02f17cd6a63d0f4b2a87b011499/src/utils/logging.h#L28-L36

To work as intended, the empty macros above need to be function macros instead of object macros, i.e.,
```C
#define FOO(...)
```
instead of
```C
#define FOO
```

**Comment by antoninbas** [comment]
Thanks for reporting this. Next time, feel free to open a PR directly for a small fix like this.
