### ISSUE TITLE
What more recent protobuf / grpc versions have people successfully used than protobuf 3.6.1 / grpc 1.17.2 ?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#567]
Those are the versions recommended in the README, and I have been using them in my script here for over a year now with success on Ubuntu 18.04 and Ubuntu 20.04 systems.

Ubuntu 22.04 is right around the corner, and as a preview I decided to try running that script on an Ubuntu 21.10 system, but there were failures while attempting to install grpc 1.17.2.

@antoninbas @smolkaj I suspect others might be using later versions of protobuf and grpc, and was curious to hear experience reports of pairs of versions that have worked well for you.

**Comment by smolkaj** [comment]
Not sure if it is related, but we have been using [this grpc workaround](https://github.com/mint570/grpc/commit/760a01337c2e05a224908fd6785809ca92a9f09f) + a grpc version from Nov 21 for PINS. We're using protobuf 3.14.

**Comment by jafingerhut** [comment]
@smolkaj Thanks for the data point.  Is there a version number for "a grpc version from Nov 21 for PINS"?  e.g. is it grpc 0.x.y, plus the workaround you link?

**Comment by smolkaj** [comment]
There is no version number I'm afraid, but it would have been somewhere between v1.42.0 and v1.43.0.
Relatedly, looks like the workaround has been merged: https://github.com/grpc/grpc/pull/28184

**Comment by jafingerhut** [comment]
Just as a reference to other related work going on, here is a PR where Antonin Bas is attempting to update a Docker image used to do CI testing on some p4lang projects to use Ubuntu 20.04 and more recent versions of protobuf and grpc: https://github.com/p4lang/third-party/pull/30

**Comment by rst0git** [comment]
I am using the grpc version 1.39.1 and protobuf version 3.14.0 installed from packages on Fedora 35.

**Comment by smolkaj** [comment]
We are currently using a [patched version of grpc](https://github.com/shak5009/grpc) to work around https://github.com/grpc/grpc/issues/17340

**Comment by jafingerhut** [comment]
I have recently experimented (only a little bit -- borrowing lots of Antonin's and other's work in choosing which versions of protobuf and grpc to try) and gotten a script that on a freshly installed Ubuntu 18.04, 20.04, or 22.04 system, it will install all of the open source P4 dev tools based upon protobuf v3.18.1 and grpc 1.43.2.  Thanks for everyone's advice.  Closing this issue.
