### ISSUE TITLE
[Question] How to parse <class 'p4.v1.p4runtime_pb2.StreamMessageResponse'>

### ISSUE THREAD

**Issue by Finnonto** [p4lang/PI#579]
Hi,

Because there is no API for register R/W on BMv2, I read register through CPU_IN and CPU_OUT packet. However, when I dumped the data which type is  <class 'p4.v1.p4runtime_pb2.StreamMessageResponse'>, I don't know how to parse the message.

the return data are like 
`packet {
  payload: "CNSRL"
  metadata {
    metadata_id: 1
    value: "\377"
  }
  metadata {
    metadata_id: 2
    value: "\242\016>s&"
  }
  metadata {
    metadata_id: 3
    value: "\242\017bZ\300"
  }
  metadata {
    metadata_id: 4
    value: "\242\n\031\241\222"
  }
`
I want to convert "values" into decimal format . I've tried to use regular expression  to parse them ,but I still want to know  if there is any formal way.

**Comment by jafingerhut** [comment]
I doubt there is a bug in the PI project related to this.  I would recommend asking P4 development related questions here intead: https://forum.p4.org

**Comment by Finnonto** [comment]
@jafingerhut  thanks a lot!

**Comment by antoninbas** [comment]
I will close this issue. You need to be familiar with the P4Runtime specification and Protobuf message formats in order to consume these messages. The metadata values are bytestrings, as described in the P4Runtime specification.
