### ISSUE TITLE
Should install instructions for PI mention that Python2 should NOT be installed?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#582]
I am not certain, but it seems in my limited testing that if one attempts to follow the recommended steps for installing PI (or behavioral-model) on a system where Python2 is installed, one or more of the install steps will detect that Python2 is installed and use it (i.e. build packages for Python2), and NOT build packages for Python3, leaving the system in a state that isn't really usable for Python3 (and perhaps not even for Python2, if both are installed -- not sure about that last statement).

If this is true, it seems worth at least a note in the README install steps to recommend that Python2 NOT be installed on a system where those install steps are performed.  Bonus points if the install scripts auto-detect and avoid using Python2, and/or just abort with an error message that installation is not supported on a system where Python2 is installed.

**Comment by rst0git** [comment]
Python 2 reached its end of life on [January 1, 2020](https://www.python.org/doc/sunset-python-2/) and the majority of Python 2 packages have been removed in the recent versions of most Linux distributions (Ubuntu, Debian, Fedora, CentOS, Alpine Linux, etc.)

> on a system where Python2 is installed, one or more of the install steps will detect that Python2 is installed and use it (i.e. build packages for Python2), and NOT build packages for Python3, leaving the system in a state that isn't really usable for Python3 

It might be better to update the install steps to use Python 3 instead.

**Comment by jafingerhut** [comment]
Oh, I know the date for when Python2 reached end of life, believe me.  I point it out to others who use my p4-guide install scripts, a few of whom seem to attempt to use them on an Ubuntu Linux system where they have installed Python2 on it before running the scripts.  They run without any errors, but the resulting system doesn't work, e.g. import statements for P4-related Python packages from a Python3 program fail, because the install scripts have detected Python2 first and installed Python2 versions of those packages instead (I am guessing, at least -- I haven't gotten to a full understanding of the install script behavior here).

If the install scripts for PI, behavioral-model, etc. were easy to change so that they never check for Python2, only Python3, and only use Python3 in their install steps, that is fine by me.  I am not pushing for that, as I do not know how much work it is to implement.  I have recently added checks in my p4-guide install scripts that if Python2 is installed on a system, they detect it at the beginning and simply fail with an appropriate error message, rather than run for an hour and a half resulting in a non-working system.

**Comment by vlstill** [comment]
Part of the detection problem could be that on older systems the `python` binary points to `python2` (and one must explicitly use `python3` to get 3). I think this is still true for Debian 10 (old-stable) and similarly old Debian systems which are actually not *that old*. (On the newer Debian/Ubuntu there is often no `python` binary unless `python-is-python3` package is installed and only `python3` exists).

**Comment by rst0git** [comment]
Thank you @jafingerhut and @vlstill, I have opened a pull request for PI with a fix for this problem: https://github.com/p4lang/PI/pull/583.

This pull request updates the minimum required version of Python from `2.7` to `3.5` in the configure script, similar to BMv2 (https://github.com/p4lang/behavioral-model/pull/960).
