### ISSUE TITLE
Can PI compile with the latest protobuf version  > 4.20 ?

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/PI#586]
Hi,

I implement my own grpc client and server application with P4runtime controller. 

However, the grpc_tools used by python-based grpc required protobuf version larger than 4.20 version and the P4runtime is utilizing the protobuf with version <  3.20. There is some conflict here. One solution is to regenerate the grpc code in P4runtime with latest protobuf version. 

Is it possible to do that ?

Best Reagards,
Johnny

**Comment by antoninbas** [comment]
I am not exactly sure what the question is about? Are you referring to the p4runtime Pypi package: https://pypi.org/project/p4runtime/?

I don't know if we want to regenerate the package code with a more recent version of Protobuf. However, we could edit https://github.com/p4lang/p4runtime/blob/bc4dea62b87d0d81eec1cffd0716a7954a53cc63/py/setup.cfg#L22-L24 to restrict the list of compatible Protobuf / gRPC versions. At the moment, the setup.cfg doesn't restrict Protobuf to 3.X, which is probably a mistake.

"gRPC tools" specifically refers to the protoc compiler. It's only needed if you want to regenerate the code yourself.

My recommendation would be to use a Python virtual environment for your project. This will let you install the "correct" version of the dependencies, without creating conflicts with your system packages.

**Comment by antoninbas** [comment]
If your application requires a recent version of Protobuf and you are not willing to use an older one, yes, you will need to regenerate the P4Runtime protos yourself.

**Comment by jafingerhut** [comment]
Closing this old issue due to no follow-up activity, so hopefully questioner had their problem resolved. Feel free to reopen this issue, or create a new one, if not.
