### ISSUE TITLE
How to use PI_ INVALID_ ID to distinguish between direct and indirect?

### ISSUE THREAD

**Issue by kanyaonieya** [p4lang/PI#589]
**In   PI/CLI/table_add.c:60**

if (t_imp == PI_INVALID_ID) {
    status = **get_entry_direct**(&t_entry);
  } else {
    status = **get_entry_indirect**(&t_entry);
  }

 ===============================
**But in PI/CLI/meter_commands.c:186**
  if (direct_t_id == PI_INVALID_ID) {
    size_t index = handle;
    rc = **pi_meter_read**(sess, dev_tgt, m_id, index, &meter_spec);
  } else {
    pi_entry_handle_t entry_handle = handle;
    rc = **pi_meter_read_direct**(sess, dev_tgt, m_id, entry_handle, &meter_spec);
  }

**Comment by antoninbas** [comment]
`t_imp` and `direct_t_id` mean 2 different things

* `t_imp` is used to store the id of the action profile / action selector, if the match-action table is "indirect". If `t_imp == PI_INVALID_ID`, then the table is not associated with an action profile or action selector, which means it is a "direct" table (i.e., a table which stores action data alongside the match entry, with no indirection), and not an "indirect" table.
* `direct_t_id` is used to indicate whether the resource (in this case, a meter) is direct (i.e., associated with a match-action table), or indirect (i.e., standalone). 

direct / indirect meter is a different concept from direct / indirect table. For example, an indirect table can be assigned a direct meter. The v1model P4 program could look like this:

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    direct_meter<bit<3> >(MeterType.packets) mtr;

    @name(".ActProfWS")
    action_selector(HashAlgorithm.crc16, 32w128, 32w16) ActProfWS;

    action port_redirect() {
        sm.egress_spec = sm.ingress_port;
        mtr.read(m.color);
    }

    table t_redirect {
        key = { sm.ingress_port : exact; }
        actions = { port_redirect; }
        implementation = ActProfWS;
        meters = mtr;
    }

    apply { t_redirect.apply(); }
}
```

To find out more about these concepts, you could consider reading the PSA specification: https://p4.org/p4-spec/docs/PSA-v1.2.html

Note that it is very rare for someone to use PI directly these days... P4Runtime is a more standard choice.
