### ISSUE TITLE
What versions of protobuf/gRPC have people successfully compiled PI with?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/PI#607]
I have successfully compiled PI with these versions of protobuf/gRPC for the past few years, and published a script that installs these versions on recent Ubuntu LTS release systems:

(a) protobuf v3.6.1, grpc v1.17.2, until early 2023 when I stopped testing on Ubuntu 18.04
(b) protobuf v3.18.1, grpc v1.43.2, currently testing every month on Ubuntu 20.04, 22.04, and have got it built successfully on 23.04 for early testing purposes to prepare for what 24.04 will be like

I tried out Ubuntu 23.10 for the first time, and it failed with combination (b) for reasons that I have not tried to debug thoroughly, but I suspect it is because the version of G++ on Ubuntu 23.10 is recent enough (G++ version 13.20) and grpc 1.43.2 is old enough (released 2022-Jan) that they are simply not compatible with each other.

On Ubuntu 23.10 I tried building the following more recent combination of versions:

(c) protobuf v3.20.3, grpc v1.54.2

Those build and install fine, but when I then try to build the code in p4lang/PI repo with these steps (which I currently successfully use with combo (b) above):

```
    git clone https://github.com/p4lang/PI
    cd PI
    git submodule update --init --recursive
    git log -n 1
    ./autogen.sh
    # Cause 'sudo make install' to install Python packages for PI in a
    # Python virtual environment, if one is in use.
    configure_python_prefix="--with-python_prefix=${PYTHON_VENV}"
    ./configure --with-proto --without-internal-rpc --without-cli --without-bmv2 ${configure_python_prefix}
    make
    sudo make install
```

it fails during the step `make`, with the last dozen or so lines of output shown below:

```
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -pthread -Wall -Wextra -g -O2   -o libpiconvertproto.la -rpath /usr/local/lib p4info_to_and_from_proto.lo ../libpiprotobuf.la -L/usr/local/lib -lprotobuf  
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/13/crtbeginS.o  .libs/p4info_to_and_from_proto.o   -Wl,-rpath -Wl,/home/andy/PI/proto/.libs ../.libs/libpiprotobuf.so -L/usr/local/lib /usr/local/lib/libprotobuf.so -L/usr/lib/gcc/x86_64-linux-gnu/13 -L/usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/13/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/13/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/13/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/crtn.o  -g -O2   -pthread -Wl,-soname -Wl,libpiconvertproto.so.0 -o .libs/libpiconvertproto.so.0.0.0
libtool: link: (cd ".libs" && rm -f "libpiconvertproto.so.0" && ln -s "libpiconvertproto.so.0.0.0" "libpiconvertproto.so.0")
libtool: link: (cd ".libs" && rm -f "libpiconvertproto.so" && ln -s "libpiconvertproto.so.0.0.0" "libpiconvertproto.so")
libtool: link: ar cr .libs/libpiconvertproto.a  p4info_to_and_from_proto.o
libtool: link: ranlib .libs/libpiconvertproto.a
libtool: link: ( cd ".libs" && rm -f "libpiconvertproto.la" && ln -s "../libpiconvertproto.la" "libpiconvertproto.la" )
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -pthread -Wall -Wextra -g -O2   -o pi_convert_p4info convert_p4info.o ./libpiconvertproto.la ../libpiprotobuf.la ../../src/libpip4info.la -L/usr/local/lib -lprotobuf  
libtool: link: g++ -Wall -Wextra -g -O2 -o .libs/pi_convert_p4info convert_p4info.o  ./.libs/libpiconvertproto.so ../.libs/libpiprotobuf.so ../../src/.libs/libpip4info.so -L/usr/local/lib /usr/local/lib/libprotobuf.so -pthread
/usr/bin/ld: ../.libs/libpiprotobuf.so: undefined reference to `google::protobuf::Any::MergeImpl(google::protobuf::Message&, google::protobuf::Message const&)'
/usr/bin/ld: ../.libs/libpiprotobuf.so: undefined reference to `google::protobuf::internal::ZeroFieldsBase::CopyImpl(google::protobuf::Message&, google::protobuf::Message const&)'
/usr/bin/ld: ../.libs/libpiprotobuf.so: undefined reference to `google::protobuf::internal::ZeroFieldsBase::MergeImpl(google::protobuf::Message&, google::protobuf::Message const&)'
/usr/bin/ld: ../.libs/libpiprotobuf.so: undefined reference to `google::protobuf::Message::CopyWithSourceCheck(google::protobuf::Message&, google::protobuf::Message const&)'
/usr/bin/ld: ../.libs/libpiprotobuf.so: undefined reference to `google::protobuf::internal::InternalMetadata::CheckedDestruct()'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:529: pi_convert_p4info] Error 1
make[4]: Leaving directory '/home/andy/PI/proto/p4info'
make[3]: *** [Makefile:1699: all-recursive] Error 1
make[3]: Leaving directory '/home/andy/PI/proto'
make[2]: *** [Makefile:739: all] Error 2
make[2]: Leaving directory '/home/andy/PI/proto'
make[1]: *** [Makefile:456: all-recursive] Error 1
make[1]: Leaving directory '/home/andy/PI'
make: *** [Makefile:388: all] Error 2
```

@smolkaj What is the most recent versions of protobuf/grpc that you have successfully built p4lang/PI with?  I can try binary search, but was hoping to avoid that.

**Comment by jafingerhut** [comment]
In answer to my own question, after some further experiments, I was able to successfully build gpc 1.51.3 from source code on all of Ubuntu 20.04, 22.04, and 23.10 systems this week, which seems to install protobuf 3.21.6 as part of its build.  My install-p4dev-v7.sh bash script mentioned here now does this: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

**Comment by alessandrocornacchia** [comment]
I also encountered this problem when trying to install PI on Ubuntu 20.04 using gRPC/protobuf versions recommended in the README. 

However, building from source gRPC 1.51.3 and protobuf 3.21.6 as suggested by @jafingerhut, doesn't seem to solve the issue for me, and I still get a lot of undefined references. My g++ compiler version is 9.4.0.

Any suggestion?

**Comment by jafingerhut** [comment]
My recommendation is to start from a _freshly installed_ Ubuntu 20.04 or 22.04 system, and follow the instructions here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

For example, the install-p4dev-v7.sh script recommended there is one I test every month on freshly installed Ubuntu 20.04 and 22.04 systems.

Those scripts _probably do not_ work well on a system where you already have installed some version of gRPC or Protobuf.  My scripts are dumb that way -- they ignore whatever might already be installed on the system, and are only tested on systems where neither of those software packages have been installed yet.

**Comment by smolkaj** [comment]
> @smolkaj What is the most recent versions of protobuf/grpc that you have successfully built p4lang/PI with?

Sorry for missing this old question.
Internally at Google, we build PI (and everything else) against protobuf/grpc "at HEAD", following Google's live-at-HEAD philosophy (https://abseil.io/about/philosophy#we-recommend-that-you-choose-to-live-at-head)
