### ISSUE TITLE
Error while installing PI - grcpp/grcpp.h : No such file or directory.

### ISSUE THREAD

**Issue by gutasiadam** [p4lang/PI#611]
Upon trying to install PI, configuring the build using the --with-proto, I run into the following error:

`gnmi_dummy.cpp:21:27: fatal error: grcpp/grcpp.h : No such file or directory.`

I followed the steps and commands written down in README for installing gRPC. I issued the following commands in the folder I cloned the PI repo into. gRPC's building docmentation states that only bazel and CMAKE is supported for building, so I modified those lines to leverage the use of cmake:

```
git clone --depth=1 -b v1.43.2 https://github.com/google/grpc.git
cd grpc/
git submodule update --init --recursive
$ mkdir -p cmake/build
$ cd cmake/build
$ cmake ../..
$ make
$ ldconfig
```

After that I tried to install using `make` on PI, that resulted in the error stated above. 
I've attached the stderr from the make command below.
[error.txt](https://github.com/p4lang/PI/files/14894215/error.txt)

**Comment by antoninbas** [comment]
You don't have an install step?
https://github.com/grpc/grpc/blob/v1.43.2/BUILDING.md#install-after-build

**Comment by jafingerhut** [comment]
Closing this old issue due to no follow-up activity, so hopefully questioner had their problem resolved.  Feel free to reopen this issue, or create a new one, if not.
